(function(){
'use strict';
const VERSION='Beta v2.3.0',LEDGER_CACHE='family-hub-v230',RATE_CACHE='family-hub-rates-v1';
const DEFAULT_TYPES=[['reminder','其他事项'],['baby','宝宝事项'],['subscription','订阅续费'],['maintenance','家庭维护'],['document','证件到期'],['warranty','保修到期'],['vehicle','车辆事项']];
let db=emptyLedger(),rates={CNY:1},ratesCached=false,filter='all',query='',editingId='',saving=false,swipe=null,blockClick=false;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function emptyLedger(){return{version:6,updatedAt:null,settings:{siteName:'Family Hub',types:DEFAULT_TYPES.map(x=>({id:x[0],name:x[1]}))},events:[]}}
function normalize(x){if(!x||!Array.isArray(x.events))return emptyLedger();x.settings=x.settings||{};if(!Array.isArray(x.settings.types)||!x.settings.types.length)x.settings.types=DEFAULT_TYPES.map(v=>({id:v[0],name:v[1]}));x.version=6;return x}
function esc(v){const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function today(){return iso(new Date())}
function uid(prefix='evt'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function typeName(id){return db.settings.types.find(x=>x.id===id)?.name||'其他事项'}
const repeats={none:'单次',daily:'每天',weekly:'每周',monthly:'每月',quarterly:'每季度',yearly:'每年'};
async function request(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt});const text=await r.text();let json={};try{json=text?JSON.parse(text):{}}catch{}if(!r.ok)throw Error(json.error||`请求失败 ${r.status}`);return json}
function readCache(){try{const x=JSON.parse(localStorage.getItem(LEDGER_CACHE)||'null');return x?.data?normalize(x.data):null}catch{return null}}
function writeCache(){try{localStorage.setItem(LEDGER_CACHE,JSON.stringify({data:db,time:Date.now()}))}catch{}}
function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1800)}
function money(n,c){try{return new Intl.NumberFormat('zh-CN',{style:'currency',currency:c||'CNY',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))}catch{return `${c||'CNY'} ${Number(n||0).toFixed(2)}`}}
function amountHtml(x){if(x.amount==null||x.amount===''||!Number.isFinite(Number(x.amount)))return'';const code=String(x.currency||'CNY').toUpperCase(),original=money(x.amount,code);if(code==='CNY')return `<div class="amount">${esc(original)}</div>`;const rate=Number(rates[code]);if(!Number.isFinite(rate)||rate<=0)return `<div class="amount">${esc(original)}</div>`;return `<div class="amount"><span>${esc(original)}</span><small>≈ ${esc(money(Number(x.amount)*rate,'CNY'))}${ratesCached?'（非实时）':''}</small></div>`}
function dayDiff(v){if(!v)return 99999;return Math.round((new Date(v+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000)}
function dateText(v){const n=dayDiff(v);if(n<0)return `逾期 ${Math.abs(n)} 天`;if(n===0)return'今天';if(n===1)return'明天';return `${n} 天后`}
function fmt(v){return v?new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',weekday:'short'}).format(new Date(v+'T12:00:00')):'未设置'}
function lunarLabel(x){return x.calendar==='lunar'?`农历 ${x.lunarMonth}月${x.lunarDay}日`:''}
function groupName(v){const n=dayDiff(v);if(n<0)return'已逾期';if(n===0)return'今天';if(n===1)return'明天';if(n<=7)return'未来 7 天';if(n<=30)return'30 天内';if(n<=365)return'一年内';return'更远以后'}
function visible(){return db.events.filter(x=>!x.archived&&(filter==='all'||(filter==='done'?x.status==='done':x.type===filter))&&(!query||[x.title,x.note,typeName(x.type)].join(' ').toLowerCase().includes(query))).sort((a,b)=>(a.status==='done')-(b.status==='done')||String(a.date||'').localeCompare(String(b.date||'')))}
function card(x){const n=dayDiff(x.date),cls=x.status==='done'?' done':n<=0?' urgent':n<=3?' soon':'';const meta=[typeName(x.type),repeats[x.repeat]||'单次',x.payment,x.note].filter(Boolean).map(esc).join(' · ');return `<article class="event${cls}" data-id="${esc(x.id)}"><div class="event-main"><div class="event-line"><b>${esc(x.title)}</b><span class="badge">${esc(typeName(x.type))}</span></div><div class="meta">${meta}</div>${amountHtml(x)}</div><div class="date"><strong>${dateText(x.date)}</strong><small>${fmt(x.date)}</small>${x.calendar==='lunar'?`<em>${esc(lunarLabel(x))}</em>`:''}</div><button class="more" data-action="menu">•••</button><div class="row-menu" hidden><button data-action="edit">编辑</button><button data-action="done">${x.status==='done'?'恢复':'完成'}</button><button data-action="delay">延期 7 天</button><button data-action="delete" class="danger">删除</button></div></article>`}
function timeline(){const g={};visible().forEach(x=>(g[groupName(x.date)]||(g[groupName(x.date)]=[])).push(x));return ['已逾期','今天','明天','未来 7 天','30 天内','一年内','更远以后'].map(k=>g[k]?`<section class="group"><div class="group-title"><b>${k}</b><span>${g[k].length}</span></div><div class="events">${g[k].map(card).join('')}</div></section>`:'').join('')||'<div class="empty"><b>暂无事项</b><span>点击右上角“新增”开始记录。</span></div>'}
function chips(){return [{id:'all',name:'全部'},...db.settings.types,{id:'done',name:'已完成'}].map(x=>`<button class="type-btn${filter===x.id?' active':''}" data-filter="${esc(x.id)}">${esc(x.name)}</button>`).join('')}
function render(){document.title=`Family Hub · 家庭事务中心 · ${VERSION}`;$('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand">Family Hub<small>家庭事务中心 · ${VERSION}</small></div><button class="ghost compact" data-action="export">导出</button><button class="ghost compact" data-action="manage">管理</button><button class="primary compact" data-action="new">＋ 新增</button></header><div class="controls"><div class="type-bar">${chips()}</div><div class="search"><input id="search" value="${esc(query)}" placeholder="搜索事项"><span>⌕</span></div></div><main class="timeline">${timeline()}</main></div>`;$('#app').hidden=false}
function typeOptions(selected){return db.settings.types.map(x=>`<option value="${esc(x.id)}"${x.id===selected?' selected':''}>${esc(x.name)}</option>`).join('')}
function openForm(x={}){editingId=x.id||'';const f=$('#eventForm');f.innerHTML=`<div class="modal"><header><h2>${editingId?'编辑事项':'新增事项'}</h2><button type="button" class="close" data-close>×</button></header><div class="grid"><label class="field full"><span>事项标题</span><input name="title" value="${esc(x.title||'')}" required></label><label class="field"><span>类型</span><select name="type">${typeOptions(x.type||db.settings.types[0].id)}</select></label><label class="field"><span>日期类型</span><select name="calendar"><option value="solar"${x.calendar!=='lunar'?' selected':''}>公历</option><option value="lunar"${x.calendar==='lunar'?' selected':''}>阴历</option></select></label><label class="field solar-field"><span>日期</span><input name="date" type="date" value="${esc(x.date||today())}" required></label><label class="field lunar-field"><span>农历月份</span><input name="lunarMonth" type="number" min="1" max="12" value="${esc(x.lunarMonth||1)}"></label><label class="field lunar-field"><span>农历日期</span><input name="lunarDay" type="number" min="1" max="30" value="${esc(x.lunarDay||1)}"></label><label class="field"><span>重复</span><select name="repeat">${Object.entries(repeats).map(([k,v])=>`<option value="${k}"${(x.repeat||'none')===k?' selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>金额（可选）</span><input name="amount" type="number" min="0" step="0.01" inputmode="decimal" value="${x.amount==null?'':Number(x.amount).toFixed(2)}"></label><label class="field"><span>币种</span><input name="currency" maxlength="8" value="${esc(x.currency||'CNY')}"></label><label class="field"><span>支付方式</span><input name="payment" value="${esc(x.payment||'')}"></label><label class="field full"><span>备注</span><textarea name="note">${esc(x.note||'')}</textarea></label></div><footer><button type="button" class="ghost" data-close>取消</button><button class="primary" type="submit">保存</button></footer></div>`;toggleCalendar();$('#eventDialog').showModal()}
function toggleCalendar(){const lunar=$('#eventForm [name=calendar]')?.value==='lunar';$$('.lunar-field').forEach(e=>e.hidden=!lunar);$$('.solar-field').forEach(e=>e.hidden=lunar)}
function openManage(){const rows=db.settings.types.map((x,i)=>`<div class="type-row" data-index="${i}"><input value="${esc(x.name)}" maxlength="20"><button type="button" data-remove-type="${i}"${db.settings.types.length<=1?' disabled':''}>删除</button></div>`).join('');$('#manageForm').innerHTML=`<div class="modal"><header><h2>管理类型</h2><button type="button" class="close" data-manage-close>×</button></header><div class="manage-body"><p>类型会显示在顶部筛选和新增表单中。</p><div id="typeRows">${rows}</div><button type="button" class="ghost" data-add-type>＋ 新增类型</button></div><footer><button type="button" class="ghost" data-manage-close>取消</button><button class="primary" type="submit">保存类型</button></footer></div>`;$('#manageDialog').showModal()}
async function lunarToSolar(month,day){const fmt=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'numeric',day:'numeric'});let d=new Date();d.setHours(12,0,0,0);for(let i=0;i<430;i++){const parts=fmt.formatToParts(d),m=Number(parts.find(p=>p.type==='month')?.value),da=Number(parts.find(p=>p.type==='day')?.value);if(m===month&&da===day)return iso(d);d.setDate(d.getDate()+1)}throw Error('无法计算该农历日期')}
async function save(){if(saving)return;saving=true;const previous=JSON.parse(JSON.stringify(db));toast('正在保存…');try{const remote=normalize(await request('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(db)}));db=remote;writeCache();render();toast('已保存')}catch(e){db=previous;render();toast('保存失败');throw e}finally{saving=false}}
function findItem(el){const c=el.closest?.('.event');return c?db.events.find(x=>x.id===c.dataset.id):null}
document.addEventListener('click',e=>{if(e.target.closest('[data-close]')){$('#eventDialog').close();return}if(e.target.closest('[data-manage-close]')){$('#manageDialog').close();return}const b=e.target.closest('button');if(!b){const c=e.target.closest('.event');if(c&&!blockClick)openForm(findItem(c));return}if(b.dataset.filter){filter=b.dataset.filter;render();return}const a=b.dataset.action;if(a==='new')openForm();else if(a==='manage')openManage();else if(a==='export'){const l=document.createElement('a');l.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));l.download='family-hub-v2.3.0.json';l.click()}else if(b.hasAttribute('data-add-type')){$('#typeRows').insertAdjacentHTML('beforeend',`<div class="type-row"><input value="新类型" maxlength="20"><button type="button" data-remove-type>删除</button></div>`)}else if(b.hasAttribute('data-remove-type'))b.closest('.type-row').remove();else{const x=findItem(b);if(!x)return;if(a==='menu'){b.nextElementSibling.hidden=!b.nextElementSibling.hidden}else if(a==='edit')openForm(x);else if(a==='done'){x.status=x.status==='done'?'pending':'done';save().catch(er=>alert(er.message))}else if(a==='delay'){const d=new Date((x.date||today())+'T12:00:00');d.setDate(d.getDate()+7);x.date=iso(d);save().catch(er=>alert(er.message))}else if(a==='delete'&&confirm(`确定删除“${x.title}”？`)){db.events=db.events.filter(v=>v.id!==x.id);save().catch(er=>alert(er.message))}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value.trim().toLowerCase();render()}if(e.target.name==='currency')e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'')});
document.addEventListener('change',e=>{if(e.target.name==='calendar')toggleCalendar()});
$('#eventForm').addEventListener('submit',async e=>{e.preventDefault();if(saving)return;const o=Object.fromEntries(new FormData(e.currentTarget));o.amount=o.amount===''?null:Math.round(Number(o.amount)*100)/100;o.calendar=o.calendar==='lunar'?'lunar':'solar';if(o.calendar==='lunar'){o.lunarMonth=Number(o.lunarMonth);o.lunarDay=Number(o.lunarDay);o.date=await lunarToSolar(o.lunarMonth,o.lunarDay)}else{o.lunarMonth=null;o.lunarDay=null}const now=new Date().toISOString(),old=editingId?db.events.find(x=>x.id===editingId):null;if(old)Object.assign(old,o,{updatedAt:now});else db.events.push({...o,id:uid(),status:'pending',createdAt:now,updatedAt:now});$('#eventDialog').close();try{await save()}catch(er){alert('保存失败：'+er.message)}});
$('#manageForm').addEventListener('submit',async e=>{e.preventDefault();const names=$$('#typeRows input').map(x=>x.value.trim()).filter(Boolean);if(!names.length)return alert('至少保留一个类型');const old=db.settings.types,used=new Set(db.events.map(x=>x.type));db.settings.types=names.map((name,i)=>old[i]?{id:old[i].id,name}:{id:uid('type'),name});const valid=new Set(db.settings.types.map(x=>x.id));db.events.forEach(x=>{if(!valid.has(x.type))x.type=db.settings.types[0].id});$('#manageDialog').close();try{await save()}catch(er){alert('保存失败：'+er.message)}});
document.addEventListener('touchstart',e=>{const c=e.target.closest('.event');if(!c||e.target.closest('button'))return;const p=e.touches[0];swipe={card:c,x:p.clientX,y:p.clientY,dx:0,moving:false}},{passive:true});
document.addEventListener('touchmove',e=>{if(!swipe)return;const p=e.touches[0],dx=p.clientX-swipe.x,dy=p.clientY-swipe.y;swipe.dx=dx;if(!swipe.moving&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy))swipe.moving=true;if(swipe.moving){e.preventDefault();swipe.card.style.transform=`translateX(${Math.max(-80,Math.min(80,dx))}px)`}},{passive:false});
document.addEventListener('touchend',()=>{if(!swipe)return;const s=swipe;swipe=null;s.card.style.transform='';if(s.moving&&Math.abs(s.dx)>=60){blockClick=true;const x=findItem(s.card);if(x){x.status=x.status==='done'?'pending':'done';save().catch(er=>alert(er.message))}setTimeout(()=>blockClick=false,350)}},{passive:true});
async function loadRates(){try{const c=JSON.parse(localStorage.getItem(RATE_CACHE)||'null');if(c?.rates){rates=c.rates;ratesCached=true}}catch{}try{const live=await request('/api/exchange-rates');if(live?.rates){rates=live.rates;ratesCached=false;localStorage.setItem(RATE_CACHE,JSON.stringify(live));render()}}catch{}}
async function boot(){const cached=readCache();if(cached){db=cached;render()}try{const s=await request('/api/auth/session');if(!s.authenticated){$('#app').hidden=true;$('#login').hidden=false;return}$('#login').hidden=true;const [ledger]=await Promise.all([request('/api/ledger'),loadRates()]);db=normalize(ledger);writeCache();render()}catch(e){if(!cached)$('#app').innerHTML=`<div class="load-error"><b>数据加载失败</b><span>${esc(e.message)}</span><button onclick="location.reload()">重新加载</button></div>`}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});await boot()}catch(er){$('#loginMessage').textContent=er.message}finally{b.disabled=false}});
boot();
})();
