(function(){
'use strict';
const VERSION='Beta v2.4.0',CACHE='family-hub-v240',RATE_CACHE='family-hub-rates-v1';
const DEFAULT_TYPES=[['reminder','其他事项'],['baby','宝宝事项'],['subscription','订阅续费'],['maintenance','家庭维护'],['document','证件到期'],['warranty','保修到期'],['vehicle','车辆事项']];
const repeatNames={none:'单次',daily:'每天',weekly:'每周',monthly:'每月',quarterly:'每季度',yearly:'每年',interval:'每隔 X 天'};
let db=empty(),rates={CNY:1},ratesCached=false,filter='all',query='',editingId='',saving=false;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function empty(){return{version:7,updatedAt:null,settings:{siteName:'Family Hub',types:DEFAULT_TYPES.map(x=>({id:x[0],name:x[1]}))},series:[],events:[]}}
function normalize(x){if(!x||!Array.isArray(x.events))return empty();x.settings=x.settings||{};x.settings.types=Array.isArray(x.settings.types)&&x.settings.types.length?x.settings.types:DEFAULT_TYPES.map(v=>({id:v[0],name:v[1]}));x.series=Array.isArray(x.series)?x.series:[];x.version=7;return x}
function esc(v){const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parse(v){return new Date(v+'T12:00:00')}
function today(){return iso(new Date())}
function uid(p='evt'){return `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`}
function typeName(id){return db.settings.types.find(x=>x.id===id)?.name||'其他事项'}
async function request(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function readCache(){try{return normalize(JSON.parse(localStorage.getItem(CACHE)||'null')?.data)}catch{return null}}
function writeCache(){try{localStorage.setItem(CACHE,JSON.stringify({data:db,time:Date.now()}))}catch{}}
function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.hidden=true,1800)}
function money(n,c){try{return new Intl.NumberFormat('zh-CN',{style:'currency',currency:c||'CNY',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))}catch{return `${c||'CNY'} ${Number(n||0).toFixed(2)}`}}
function amountHtml(x){if(x.amount==null||!Number.isFinite(Number(x.amount)))return'';const c=String(x.currency||'CNY').toUpperCase(),o=money(x.amount,c);if(c==='CNY'||!Number.isFinite(Number(rates[c])))return `<div class="amount">${esc(o)}</div>`;return `<div class="amount"><span>${esc(o)}</span><small>≈ ${esc(money(Number(x.amount)*Number(rates[c]),'CNY'))}${ratesCached?'（非实时）':''}</small></div>`}
function dayDiff(v){return Math.round((parse(v)-parse(today()))/86400000)}
function dateText(v){const n=dayDiff(v);if(n<0)return`逾期 ${Math.abs(n)} 天`;if(n===0)return'今天';if(n===1)return'明天';return`${n} 天后`}
function fmt(v){return new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',weekday:'short'}).format(parse(v))}
function group(v){const n=dayDiff(v);if(n<0)return'已逾期';if(n===0)return'今天';if(n===1)return'明天';if(n<=7)return'未来 7 天';if(n<=30)return'30 天内';if(n<=365)return'一年内';return'更远以后'}
function seriesOf(x){return x.seriesId?db.series.find(s=>s.id===x.seriesId):null}
function visible(){return db.events.filter(x=>!x.archived&&(filter==='all'||(filter==='done'?x.status==='done':x.type===filter))&&(!query||[x.title,x.note,typeName(x.type)].join(' ').toLowerCase().includes(query))).sort((a,b)=>(a.status==='done')-(b.status==='done')||String(a.date).localeCompare(String(b.date)))}
function card(x){const n=dayDiff(x.date),cls=x.status==='done'?' done':n<=0?' urgent':n<=3?' soon':'',s=seriesOf(x);const cycle=s?repeatNames[s.repeat]:'单次';const meta=[typeName(x.type),cycle,x.payment,x.note].filter(Boolean).map(esc).join(' · ');return `<article class="event${cls}" data-id="${esc(x.id)}"><div class="event-main"><div class="event-line"><b>${esc(x.title)}</b><span class="badge">${esc(typeName(x.type))}</span></div><div class="meta">${meta}</div>${amountHtml(x)}</div><div class="date"><strong>${dateText(x.date)}</strong><small>${fmt(x.date)}</small>${x.calendar==='lunar'?`<em>农历 ${x.lunarMonth}月${x.lunarDay}日</em>`:''}</div><button class="more" data-action="menu">•••</button><div class="row-menu" hidden><button data-action="edit">编辑本次</button><button data-action="done">${x.status==='done'?'恢复':'完成'}</button><button data-action="delay">延期 7 天</button><button data-action="delete" class="danger">删除本次</button></div></article>`}
function timeline(){const g={};visible().forEach(x=>(g[group(x.date)]||(g[group(x.date)]=[])).push(x));return ['已逾期','今天','明天','未来 7 天','30 天内','一年内','更远以后'].map(k=>g[k]?`<section class="group"><div class="group-title"><b>${k}</b><span>${g[k].length}</span></div><div class="events">${g[k].map(card).join('')}</div></section>`:'').join('')||'<div class="empty"><b>暂无事项</b><span>点击右上角“新增”开始记录。</span></div>'}
function chips(){return [{id:'all',name:'全部'},...db.settings.types,{id:'done',name:'已完成'}].map(x=>`<button class="type-btn${filter===x.id?' active':''}" data-filter="${esc(x.id)}">${esc(x.name)}</button>`).join('')}
function render(){document.title=`Family Hub · 家庭事务中心 · ${VERSION}`;$('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand">Family Hub<small>家庭事务中心 · ${VERSION}</small></div><button class="ghost compact" data-action="export">导出</button><button class="ghost compact" data-action="manage">管理</button><button class="primary compact" data-action="new">＋ 新增</button></header><div class="controls"><div class="type-bar">${chips()}</div><div class="search"><input id="search" value="${esc(query)}" placeholder="搜索事项"><span>⌕</span></div></div><main class="timeline">${timeline()}</main></div>`;$('#app').hidden=false}
function typeOptions(v){return db.settings.types.map(x=>`<option value="${esc(x.id)}"${x.id===v?' selected':''}>${esc(x.name)}</option>`).join('')}
function repeatOptions(v){return Object.entries(repeatNames).map(([k,n])=>`<option value="${k}"${k===v?' selected':''}>${n}</option>`).join('')}
function openForm(x={}){editingId=x.id||'';const s=seriesOf(x),repeat=editingId?'none':(s?.repeat||'none');$('#eventForm').innerHTML=`<div class="modal"><header><h2>${editingId?'编辑本次事项':'新增事项'}</h2><button type="button" class="close" data-close>×</button></header><div class="grid"><label class="field full"><span>事项标题</span><input name="title" value="${esc(x.title||'')}" required></label><label class="field"><span>类型</span><select name="type">${typeOptions(x.type||db.settings.types[0].id)}</select></label><label class="field"><span>日期类型</span><select name="calendar"><option value="solar"${x.calendar!=='lunar'?' selected':''}>公历</option><option value="lunar"${x.calendar==='lunar'?' selected':''}>阴历</option></select></label><label class="field solar-field"><span>${editingId?'日期':'起始日期'}</span><input name="date" type="date" value="${esc(x.date||today())}" required></label><label class="field lunar-field"><span>农历月份</span><input name="lunarMonth" type="number" min="1" max="12" value="${x.lunarMonth||1}"></label><label class="field lunar-field"><span>农历日期</span><input name="lunarDay" type="number" min="1" max="30" value="${x.lunarDay||1}"></label>${editingId?'':`<label class="field"><span>循环周期</span><select name="repeat">${repeatOptions(repeat)}</select></label><label class="field repeat-field"><span>结束日期（可选）</span><input name="endDate" type="date"></label><label class="field interval-field"><span>每隔多少天</span><input name="intervalDays" type="number" min="1" max="3650" value="7"></label>`}<label class="field"><span>金额（可选）</span><input name="amount" type="number" min="0" step="0.01" inputmode="decimal" value="${x.amount==null?'':Number(x.amount).toFixed(2)}"></label><label class="field"><span>币种</span><input name="currency" value="${esc(x.currency||'CNY')}"></label><label class="field"><span>支付方式</span><input name="payment" value="${esc(x.payment||'')}"></label><label class="field full"><span>备注</span><textarea name="note">${esc(x.note||'')}</textarea></label></div><footer><button type="button" class="ghost" data-close>取消</button><button class="primary" type="submit">保存</button></footer></div>`;toggleFields();$('#eventDialog').showModal()}
function toggleFields(){const cal=$('#eventForm [name=calendar]')?.value,lunar=cal==='lunar',rep=$('#eventForm [name=repeat]')?.value||'none';$$('.lunar-field').forEach(e=>e.hidden=!lunar);$$('.solar-field').forEach(e=>e.hidden=lunar);$$('.repeat-field').forEach(e=>e.hidden=rep==='none');$$('.interval-field').forEach(e=>e.hidden=rep!=='interval')}
function addPeriod(date,repeat,interval,startDay){const d=new Date(date);if(repeat==='daily')d.setDate(d.getDate()+1);else if(repeat==='weekly')d.setDate(d.getDate()+7);else if(repeat==='interval')d.setDate(d.getDate()+interval);else{const months=repeat==='monthly'?1:repeat==='quarterly'?3:12;d.setDate(1);d.setMonth(d.getMonth()+months);d.setDate(Math.min(startDay,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()))}return d}
async function lunarDates(month,day,start,end){const f=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'numeric',day:'numeric'}),out=[];let d=parse(start),limit=parse(end);while(d<=limit&&out.length<1000){const p=f.formatToParts(d),m=Number(p.find(x=>x.type==='month')?.value),da=Number(p.find(x=>x.type==='day')?.value);if(m===month&&da===day)out.push(iso(d));d.setDate(d.getDate()+1)}return out}
async function occurrenceDates(o){const start=o.date,end=o.endDate||iso(new Date(parse(start).setFullYear(parse(start).getFullYear()+1)));if(parse(end)<parse(start))throw Error('结束日期不能早于起始日期');if(o.repeat==='none')return[start];if(o.calendar==='lunar'){if(o.repeat!=='yearly')throw Error('阴历循环目前仅支持每年');return lunarDates(Number(o.lunarMonth),Number(o.lunarDay),start,end)}const out=[],startDay=parse(start).getDate();let d=parse(start);while(d<=parse(end)&&out.length<1000){out.push(iso(d));d=addPeriod(d,o.repeat,Number(o.intervalDays)||1,startDay)}if(out.length>=1000)throw Error('循环生成超过 1000 条，请缩短结束日期');return out}
async function save(){if(saving)return;saving=true;const old=JSON.parse(JSON.stringify(db));toast('正在保存…');try{db=normalize(await request('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(db)}));writeCache();render();toast('已保存')}catch(e){db=old;render();toast('保存失败');throw e}finally{saving=false}}
function findItem(el){const c=el.closest?.('.event');return c?db.events.find(x=>x.id===c.dataset.id):null}
function openManage(){const rows=db.settings.types.map(x=>`<div class="type-row" data-id="${esc(x.id)}"><input value="${esc(x.name)}" maxlength="20"><button type="button" data-remove>删除</button></div>`).join('');$('#manageForm').innerHTML=`<div class="modal"><header><h2>管理类型</h2><button type="button" class="close" data-manage-close>×</button></header><div class="manage-body"><div id="typeRows">${rows}</div><button type="button" class="ghost" data-add>＋ 新增类型</button></div><footer><button type="button" class="ghost" data-manage-close>取消</button><button class="primary">保存类型</button></footer></div>`;$('#manageDialog').showModal()}
document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))return $('#eventDialog').close();if(e.target.closest('[data-manage-close]'))return $('#manageDialog').close();const b=e.target.closest('button');if(!b){const c=e.target.closest('.event');if(c)openForm(findItem(c));return}if(b.dataset.filter){filter=b.dataset.filter;render();return}const a=b.dataset.action;if(a==='new')openForm();else if(a==='manage')openManage();else if(a==='export'){const l=document.createElement('a');l.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));l.download='family-hub-v2.4.0.json';l.click()}else if(b.hasAttribute('data-add'))$('#typeRows').insertAdjacentHTML('beforeend','<div class="type-row"><input value="新类型" maxlength="20"><button type="button" data-remove>删除</button></div>');else if(b.hasAttribute('data-remove'))b.closest('.type-row').remove();else{const x=findItem(b);if(!x)return;if(a==='menu')b.nextElementSibling.hidden=!b.nextElementSibling.hidden;else if(a==='edit')openForm(x);else if(a==='done'){x.status=x.status==='done'?'pending':'done';save().catch(er=>alert(er.message))}else if(a==='delay'){const d=parse(x.date);d.setDate(d.getDate()+7);x.date=iso(d);save().catch(er=>alert(er.message))}else if(a==='delete'&&confirm(`确定删除本次“${x.title}”？`)){db.events=db.events.filter(v=>v.id!==x.id);save().catch(er=>alert(er.message))}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value.trim().toLowerCase();render()}if(e.target.name==='currency')e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'')});
document.addEventListener('change',e=>{if(['calendar','repeat'].includes(e.target.name))toggleFields()});
$('#eventForm').addEventListener('submit',async e=>{e.preventDefault();if(saving)return;const o=Object.fromEntries(new FormData(e.currentTarget));o.amount=o.amount===''?null:Math.round(Number(o.amount)*100)/100;o.calendar=o.calendar==='lunar'?'lunar':'solar';o.lunarMonth=o.calendar==='lunar'?Number(o.lunarMonth):null;o.lunarDay=o.calendar==='lunar'?Number(o.lunarDay):null;const now=new Date().toISOString();if(editingId){const x=db.events.find(v=>v.id===editingId);Object.assign(x,o,{repeat:undefined,updatedAt:now});delete x.endDate;delete x.intervalDays}else{const dates=await occurrenceDates(o),seriesId=o.repeat==='none'?null:uid('series');if(seriesId)db.series.push({...o,id:seriesId,startDate:dates[0],date:dates[0],endDate:o.endDate||iso(new Date(parse(dates[0]).setFullYear(parse(dates[0]).getFullYear()+1))),intervalDays:Number(o.intervalDays)||1,active:true,createdAt:now,updatedAt:now});for(const d of dates)db.events.push({title:o.title,type:o.type,date:d,occurrenceDate:d,seriesId,calendar:o.calendar,lunarMonth:o.lunarMonth,lunarDay:o.lunarDay,status:'pending',amount:o.amount,currency:o.currency||'CNY',payment:o.payment||'',note:o.note||'',id:uid(),createdAt:now,updatedAt:now})}$('#eventDialog').close();try{await save()}catch(er){alert('保存失败：'+er.message)}});
$('#manageForm').addEventListener('submit',async e=>{e.preventDefault();const rows=$$('#typeRows .type-row'),types=rows.map(r=>({id:r.dataset.id||uid('type'),name:$('input',r).value.trim()})).filter(x=>x.name);if(!types.length)return alert('至少保留一个类型');db.settings.types=types;const valid=new Set(types.map(x=>x.id));db.events.forEach(x=>{if(!valid.has(x.type))x.type=types[0].id});db.series.forEach(x=>{if(!valid.has(x.type))x.type=types[0].id});$('#manageDialog').close();try{await save()}catch(er){alert(er.message)}});
async function loadRates(){try{const c=JSON.parse(localStorage.getItem(RATE_CACHE)||'null');if(c?.rates){rates=c.rates;ratesCached=true}}catch{}try{const live=await request('/api/exchange-rates');if(live.rates){rates=live.rates;ratesCached=false;localStorage.setItem(RATE_CACHE,JSON.stringify(live));render()}}catch{}}
async function boot(){const c=readCache();if(c?.events){db=c;render()}try{const s=await request('/api/auth/session');if(!s.authenticated){$('#app').hidden=true;$('#login').hidden=false;return}$('#login').hidden=true;db=normalize(await request('/api/ledger'));writeCache();render();loadRates()}catch(e){if(!c)$('#app').innerHTML=`<div class="load-error"><b>数据加载失败</b><span>${esc(e.message)}</span><button onclick="location.reload()">重新加载</button></div>`}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});await boot()}catch(er){$('#loginMessage').textContent=er.message}finally{b.disabled=false}});
boot();
})();
