import { dayDiff, nextDue, repeatLabel } from "/schedule.js";
const $=(s,r=document)=>r.querySelector(s);let data,active="overview";
const meta={overview:["总览","⌘"],subscriptions:["账单与订阅","◒"],warranties:["物品保修与维修","⌂"],reminders:["倒计时与提醒","◷"]};
async function req(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"请求失败");return j}
const days=v=>!v?null:dayDiff(v);
const fmt=v=>v?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(`${v}T00:00:00`)):"未设置";
const money=v=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:2}).format(v||0);
const esc=v=>{const e=document.createElement("i");e.textContent=v||"";return e.innerHTML};
function setName(){const n=data.settings.siteName||"HomeLedger";$("#siteName").textContent=n;document.title=`${n} · 家庭账本`;$(".brand i").textContent=[...n][0]?.toUpperCase()||"H"}
function makeTabs(){const tabs=$("#tabs");tabs.replaceChildren();["overview",...data.settings.moduleOrder].forEach(k=>{const b=document.createElement("button");b.className=k===active?"active":"";b.textContent=meta[k][0];b.onclick=()=>{active=k;render()};tabs.append(b)})}
const dateText=d=>d<0?`已逾期 ${Math.abs(d)} 天`:d===0?"今天":d===1?"明天":`${d} 天后`;
function actionItems(){return [...data.subscriptions.filter(x=>!x.archived&&x.nextDate).map(x=>({type:"subscriptions",item:x,date:x.nextDate,d:days(x.nextDate),title:`支付 ${money(x.amount)}`,sub:`${x.cycle==="yearly"?"年度续费":"订阅扣费"} · ${x.category||"未分类"}`})),...data.warranties.filter(x=>!x.archived&&x.warrantyUntil).map(x=>({type:"warranties",item:x,date:x.warrantyUntil,d:days(x.warrantyUntil),title:"保修即将到期",sub:[x.brand,x.model,x.location].filter(Boolean).join(" · ")||"家庭物品"})),...data.reminders.filter(x=>!x.archived&&!x.done).map(x=>{const date=nextDue(x);return date?{type:"reminders",item:x,date,d:days(date),title:"待处理提醒",sub:repeatLabel(x)}:null}).filter(Boolean)].sort((a,b)=>a.d-b.d)}
function overviewCard(x){return `<button class="action-card ${x.d<=0?"urgent":""}" data-tab="${x.type}"><span class="action-icon">${meta[x.type][1]}</span><span class="action-copy"><b>${esc(x.item.name)}</b><small>${esc(x.title)} · ${esc(x.sub)}</small></span><span class="action-date">${dateText(x.d)}<small>${fmt(x.date)}</small></span></button>`}
function renderOverview(){const root=$("#module"),items=actionItems(),groups=[["已逾期",x=>x.d<0],["今天要处理",x=>x.d===0],["未来 7 天",x=>x.d>0&&x.d<=7],["本月内",x=>x.d>7&&x.d<=30],["之后",x=>x.d>30]];root.innerHTML=`<div class="overview-intro"><span>接下来该做什么</span><small>${items.length?`已按时间整理 ${items.length} 项待处理事项`:"暂时没有临近事项，家庭档案一切正常"}</small></div><div class="timeline">${groups.map(([title,fn])=>{const list=items.filter(fn);return list.length?`<section class="time-group"><h2>${title}<small>${list.length}</small></h2><div class="action-grid">${list.map(overviewCard).join("")}</div></section>`:""}).join("")}${!items.length?'<div class="empty"><b>✓</b><h2>近期没有需要处理的事项</h2><p>新增订阅、保修或提醒后，这里会自动按时间提示你。</p><a href="/admin/">前往管理页</a></div>':""}</div>`;root.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{active=x.dataset.tab;render();window.scrollTo({top:0,behavior:"smooth"})})}
function subscriptionCard(x){const d=x.nextDate?days(x.nextDate):null;return `<article class="record subscription ${x.archived?"muted":""}"><div class="record-icon">◒</div><div><h3>${esc(x.name)}</h3><p>${esc(x.category||"未分类")} · ${x.autoRenew?"自动续费":"手动续费"}${x.payment?` · ${esc(x.payment)}`:""}</p></div><div class="amount"><b>${money(x.amount)}</b><small>${x.cycle==="yearly"?"每年":x.cycle==="once"?"一次性":"每月"}</small></div><aside class="${d!==null&&d<=7?"notice":""}">${x.nextDate?dateText(d):"未设日期"}<small>${x.nextDate?fmt(x.nextDate):""}</small></aside></article>`}
function warrantyCard(x){const d=x.warrantyUntil?days(x.warrantyUntil):null;return `<article class="record warranty ${x.archived?"muted":""}"><div class="record-icon">⌂</div><div><h3>${esc(x.name)}</h3><p>${esc([x.brand,x.model,x.location].filter(Boolean).join(" · ")||"家庭物品")}</p></div><aside class="${d!==null&&d<=30?"notice":""}">${x.warrantyUntil?d<0?"保修已结束":d<=30?"临近过保":"保障中":"未设保修"}<small>${x.warrantyUntil?`至 ${fmt(x.warrantyUntil)}`:""}</small></aside></article>`}
function reminderCard(x){const due=nextDue(x),d=due?days(due):null;return `<article class="record reminder ${x.done?"muted done":""}"><div class="record-icon">${x.done?"✓":"◷"}</div><div><h3>${esc(x.name)}</h3><p>${esc(x.category||"未分类")} · ${esc(repeatLabel(x))}</p></div><aside class="${d!==null&&d<=x.advanceDays?"notice":""}">${x.done?"已完成":due?dateText(d):"未设日期"}<small>${due?fmt(due):""}</small></aside></article>`}
function renderModule(){if(active==="overview")return renderOverview();const list=data[active].filter(x=>!x.archived);const root=$("#module"),card=active==="subscriptions"?subscriptionCard:active==="warranties"?warrantyCard:reminderCard;const due=active==="subscriptions"?list.filter(x=>x.nextDate&&days(x.nextDate)<=30).length:active==="warranties"?list.filter(x=>x.warrantyUntil&&days(x.warrantyUntil)<=60).length:list.filter(x=>!x.done&&nextDue(x)&&days(nextDue(x))<=30).length;root.innerHTML=`<div class="module-meta"><span>${active==="subscriptions"?`每月预计 ${money(list.reduce((s,x)=>s+x.amount/(x.cycle==="yearly"?12:1),0))}`:active==="warranties"?`已记录 ${list.length} 件家庭物品`:`待完成 ${list.filter(x=>!x.done).length} 项`}</span><small>${due?`其中 ${due} 项近期需要关注`:"当前没有临近事项"}</small></div>${list.length?`<div class="records ${active}">${list.map(card).join("")}</div>`:`<div class="empty"><b>⌁</b><h2>还没有${meta[active][0]}</h2><p>直接在这里新增第一条记录。</p></div>`}<button class="add-record" id="quickAddButton">+ 新增${meta[active][0]}</button>`;$("#quickAddButton").onclick=()=>openQuick(active)}
function render(){setName();makeTabs();renderModule()}
async function init(){try{const s=await req("/api/auth/session",{cache:"no-store"});if(!s.authenticated){$("#login").hidden=false;return}data=await req("/api/ledger",{cache:"no-store"});$("#app").hidden=false;render()}catch{$("#login").hidden=false;$("#loginMessage").textContent="服务暂不可用，请稍后重试。"}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const b=$("button",e.currentTarget);b.disabled=true;$("#loginMessage").textContent="";try{await req("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#password").value})});const s=await req("/api/auth/session",{cache:"no-store"});if(!s.authenticated)throw Error("登录状态未保存，请确认浏览器允许 Cookie。");data=await req("/api/ledger",{cache:"no-store"});$("#login").hidden=true;$("#app").hidden=false;render()}catch(e){$("#loginMessage").textContent=e.message}finally{b.disabled=false}};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`;
const field=(label,name,value="",type="text",options="",extra="")=>`<div class="field"><label>${label}</label>${type==="select"?`<select name="${name}">${options}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${extra}>`}</div>`;
const repeatOptions='<option value="none">不重复（单次）</option><option value="weekly">每周</option><option value="monthly">每月</option><option value="quarterly">每季度</option><option value="yearly">每年</option><option value="interval">每隔指定天数</option>',monthOptions=Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1} 月</option>`).join(""),dayOptions=Array.from({length:30},(_,i)=>`<option value="${i+1}">${i+1} 日</option>`).join("");
function openQuick(kind){const today=new Date().toISOString().slice(0,10);$("#quickTitle").textContent=`新增${meta[kind][0]}`;let html=`<div class="two">${field("名称","name")}${field("分类","category")}</div>`;if(kind==="subscriptions")html+=`<div class="two">${field("金额","amount",0,"number")}${field("周期","cycle","monthly","select",'<option value="monthly">每月</option><option value="yearly">每年</option><option value="once">一次性</option>')}</div><div class="two">${field("下次扣费日","nextDate",today,"date")}${field("支付方式","payment")}</div>`;if(kind==="warranties")html+=`<div class="two">${field("品牌","brand")}${field("型号","model")}</div><div class="two">${field("购买日期","purchaseDate",today,"date")}${field("保修截止","warrantyUntil",today,"date")}</div>`;if(kind==="reminders")html+=`<div class="two">${field("日历","calendar","gregorian","select",'<option value="gregorian">公历</option><option value="lunar">农历（每年）</option>')}${field("提前提醒天数","advanceDays",0,"number",'', 'min="0"')}</div><div id="qgreg"><div class="two">${field("开始日期","targetDate",today,"date")}${field("重复规则","repeat","none","select",repeatOptions)}</div><div class="two qinterval" hidden>${field("每隔天数","intervalDays",1,"number",'', 'min="1"')}<span class="hint">按开始日期循环计算</span></div></div><div id="qlunar" hidden><div class="two">${field("农历月份","lunarMonth",1,"select",monthOptions)}${field("农历日期","lunarDay",1,"select",dayOptions)}</div><label class="check"><input type="checkbox" name="lunarLeap"> 闰月</label><span class="hint">农历提醒按每年对应日期自动计算。</span></div>`;$("#quickFields").innerHTML=html;const cal=$("[name=calendar]"),rep=$("[name=repeat]");if(cal){const sync=()=>{$("#qgreg").hidden=cal.value==="lunar";$("#qlunar").hidden=cal.value!=="lunar"};cal.onchange=sync;rep.onchange=()=>$(".qinterval").hidden=rep.value!=="interval";sync()}$("#quickAdd").dataset.kind=kind;$("#quickAdd").showModal()}
$("#quickAddForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),kind=$("#quickAdd").dataset.kind,name=String(f.get("name")||"").trim();if(!name)return;const item={id:uid(),name,category:String(f.get("category")||""),note:"",archived:false};for(const[k,v]of f)item[k]=v;if(kind==="subscriptions"){item.amount=Number(item.amount)||0;item.autoRenew=true;item.currency="CNY"}if(kind==="reminders"){item.advanceDays=Math.max(0,Number(item.advanceDays)||0);item.intervalDays=Math.max(1,Number(item.intervalDays)||1);item.lunarLeap=f.get("lunarLeap")==="on";item.done=false}data[kind].push(item);data=await req("/api/ledger",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});$("#quickAdd").close();render()};document.querySelectorAll("[data-quick-close]").forEach(b=>b.onclick=()=>$("#quickAdd").close());init();
