const $=(s,r=document)=>r.querySelector(s);let data,active="subscriptions";const meta={subscriptions:["账单与订阅","◒"],warranties:["物品保修与维修","⌂"],reminders:["倒计时与提醒","◷"]};
async function req(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"请求失败");return j}
const days=v=>{if(!v)return null;return Math.ceil((new Date(`${v}T00:00:00`)-new Date())/864e5)};const fmt=v=>v?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(`${v}T00:00:00`)):"未设置";const money=v=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:2}).format(v||0);
function setName(){const n=data.settings.siteName||"HomeLedger";$("#siteName").textContent=n;document.title=`${n} · 家庭账本`;$(".brand i").textContent=[...n][0]?.toUpperCase()||"H"}
function makeTabs(){const tabs=$("#tabs");tabs.replaceChildren();data.settings.moduleOrder.forEach(k=>{const b=document.createElement("button");b.className=k===active?"active":"";b.textContent=meta[k][0];b.onclick=()=>{active=k;render()};tabs.append(b)})}
function renderSummary(){const total=data.subscriptions.filter(x=>!x.archived).reduce((s,x)=>s+x.amount/(x.cycle==="yearly"?12:1),0);const notices=[...data.subscriptions.filter(x=>x.nextDate&&days(x.nextDate)<=30).map(x=>({n:x.name,d:days(x.nextDate),t:"续费"})),...data.warranties.filter(x=>x.warrantyUntil&&days(x.warrantyUntil)<=60).map(x=>({n:x.name,d:days(x.warrantyUntil),t:"保修"})),...data.reminders.filter(x=>!x.done&&x.targetDate&&days(x.targetDate)<=30).map(x=>({n:x.name,d:days(x.targetDate),t:"提醒"}))].sort((a,b)=>a.d-b.d);$("#summary").innerHTML=`<article><small>订阅月均</small><strong>${money(total)}</strong><span>${data.subscriptions.filter(x=>!x.archived).length} 项有效订阅</span></article><article><small>近期事项</small><strong>${notices.length}</strong><span>${notices[0]?`${notices[0].n} · ${notices[0].d<0?"已逾期":`${notices[0].d} 天后`}`:"暂无近期事项"}</span></article><article><small>家庭档案</small><strong>${data.warranties.length}</strong><span>件物品已记录</span></article>`}
function card(x,type){let tag,detail,late=false;if(type==="subscriptions"){tag=x.nextDate?fmt(x.nextDate):"未设续费日期";detail=`${money(x.amount)} · ${x.cycle==="yearly"?"每年":x.cycle==="once"?"一次性":"每月"}`;late=x.nextDate&&days(x.nextDate)<=7}else if(type==="warranties"){tag=x.warrantyUntil?`保修至 ${fmt(x.warrantyUntil)}`:"未设保修期限";detail=[x.brand,x.model,x.location].filter(Boolean).join(" · ")||"家庭物品";late=x.warrantyUntil&&days(x.warrantyUntil)<=30}else{tag=x.targetDate?fmt(x.targetDate):"未设日期";detail=x.repeat==="yearly"?"每年重复":x.repeat==="monthly"?"每月重复":"单次事项";late=x.targetDate&&days(x.targetDate)<=x.advanceDays}return `<article class="record ${x.archived||x.done?"muted":""}"><div class="record-icon">${meta[type][1]}</div><div><h3>${esc(x.name)}</h3><p>${esc(detail)}</p></div><aside class="${late?"notice":""}">${esc(tag)}<small>${esc(x.category||"未分类")}</small></aside></article>`}
function esc(v){const e=document.createElement("i");e.textContent=v||"";return e.innerHTML}function renderModule(){const list=data[active].filter(x=>!x.archived);const root=$("#module");if(!list.length){const n=$("#empty").content.firstElementChild.cloneNode(true);$("h2",n).textContent=`还没有${meta[active][0]}`;$("p",n).textContent="前往管理页，添加第一条记录。";root.replaceChildren(n);return}root.innerHTML=`<div class="section-title"><div><p>${meta[active][0]}</p><h2>${list.length} 条记录</h2></div><a href="/admin/">+ 新增</a></div><div class="records">${list.map(x=>card(x,active)).join("")}</div>`}function render(){setName();makeTabs();renderSummary();renderModule()}
async function init(){try{const s=await req("/api/auth/session",{cache:"no-store"});if(!s.authenticated){$("#login").hidden=false;return}data=await req("/api/ledger",{cache:"no-store"});$("#app").hidden=false;$("#today").textContent=new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date());render()}catch{$("#login").hidden=false;$("#loginMessage").textContent="服务暂不可用，请稍后重试。"}}$("#loginForm").onsubmit=async e=>{e.preventDefault();const b=$("button",e.currentTarget);b.disabled=true;$("#loginMessage").textContent="";try{await req("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#password").value})});const s=await req("/api/auth/session",{cache:"no-store"});if(!s.authenticated)throw Error("登录状态未保存，请确认浏览器允许 Cookie。");data=await req("/api/ledger",{cache:"no-store"});$("#login").hidden=true;$("#app").hidden=false;render()}catch(e){$("#loginMessage").textContent=e.message}finally{b.disabled=false}};init();
