(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function applyTheme(v){document.documentElement.dataset.theme=v;localStorage.setItem('family-hub-theme',v);if(v==='dark')document.documentElement.style.colorScheme='dark';else document.documentElement.style.colorScheme='light'}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal v25-modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-v25-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;d.showModal()}
async function showStats(){const s=await req('/api/stats');modal('数据概览',`<div class="v25-stats">${[['今天',s.today],['未来7天',s.next7],['未来30天',s.next30],['逾期',s.overdue],['已完成',s.done],['全部事项',s.total],['订阅',s.subscriptions],['一年内人民币',`¥${Number(s.annualCny||0).toFixed(2)}`]].map(x=>`<div><b>${esc(x[1])}</b><span>${x[0]}</span></div>`).join('')}</div>`)}
async function showTools(){modal('管理中心',`<div class="v25-tools"><button data-v25="stats">数据概览</button><button data-v25="templates">事项模板</button><button data-v25="series">循环规则</button><button data-v25="trash">回收站</button><button data-v25="logs">操作日志</button><button data-v25="export">导出数据</button><button data-v25="import">导入 JSON</button><button data-v25="calendar">导出日历</button><button data-v25="backup">查看备份</button><button data-v25="theme">切换主题</button><button data-v25="api">API 说明</button></div>`)}
async function showTemplates(){const x=await req('/api/templates');modal('事项模板',`<div class="v25-list">${x.templates.map(t=>`<div><b>${esc(t.name)}</b><small>${(t.items||[]).length} 个事项</small><button data-template="${esc(t.id)}">应用</button></div>`).join('')}</div>`)}
async function showTrash(){const d=await req('/api/ledger'),now=Date.now();d.trash=(d.trash||[]).filter(x=>!x.deletedAt||now-new Date(x.deletedAt).getTime()<30*86400000);modal('回收站（保留30天）',`<div class="v25-list">${d.trash.length?d.trash.map(x=>`<div><b>${esc(x.title)}</b><small>${esc(x.date||'')}</small><button data-restore="${esc(x.id)}">恢复</button></div>`).join(''):'<p>回收站为空</p>'}</div>`)}
async function showLogs(){const d=await req('/api/ledger');modal('操作日志',`<div class="v25-log">${(d.logs||[]).slice().reverse().slice(0,100).map(x=>`<div><b>${esc(x.action)}</b><span>${esc(x.title||x.detail||'')}</span><small>${new Date(x.at).toLocaleString('zh-CN')}</small></div>`).join('')||'<p>暂无日志</p>'}</div>`)}
async function showSeries(){const d=await req('/api/ledger');modal('循环规则',`<div class="v25-list">${(d.series||[]).map(s=>`<div><b>${esc(s.title)}</b><small>${esc(s.repeat)} · ${esc(s.startDate)} 至 ${esc(s.endDate)}</small><button data-series-toggle="${esc(s.id)}">${s.active===false?'恢复':'暂停'}</button><button data-series-delete="${esc(s.id)}">删除未来实例</button></div>`).join('')||'<p>暂无循环规则</p>'}</div>`)}
async function exportData(){const d=await req('/api/ledger'),choice=prompt('输入导出格式：json / csv / markdown','json');if(choice==='csv'){const rows=[['标题','类型','日期','状态','金额','币种','备注'],...d.events.map(x=>[x.title,x.type,x.date,x.status,x.amount??'',x.currency,x.note])];download('family-hub.csv',rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}else if(choice==='markdown'){download('family-hub.md',['# Family Hub','',...d.events.map(x=>`- [${x.status==='done'?'x':' '}] ${x.date} ${x.title}（${x.type}）${x.note?` — ${x.note}`:''}`)].join('\n'),'text/markdown')}else download('family-hub.json',JSON.stringify(d,null,2),'application/json')}
function importData(){modal('导入 JSON','<textarea id="v25Import" style="width:100%;min-height:240px" placeholder="粘贴完整 JSON 数据"></textarea>','<button type="button" class="ghost" data-v25-close>取消</button><button type="button" class="primary" data-import-save>导入并覆盖</button>')}
function apiDocs(){modal('API 接口',`<div class="v25-api"><p>在 EdgeOne 增加环境变量 <code>API_KEY</code>，请求携带 <code>X-API-Key</code> 或 <code>Authorization: Bearer</code>。</p><code>GET /api/types</code><code>GET /api/events?days=30&type=baby&status=pending</code><code>POST /api/events</code><code>PATCH /api/events?id=事项ID</code><code>DELETE /api/events?id=事项ID</code><code>GET /api/today</code><code>GET /api/stats</code><code>GET /api/calendar?days=365</code></div>`)}
async function enhance(){const top=$('.top');if(!top||top.dataset.v25)return;top.dataset.v25='1';const b=document.createElement('button');b.className='ghost compact';b.textContent='功能';b.dataset.v25='tools';const primary=top.querySelector('[data-action="new"]');top.insertBefore(b,primary);if(!$('.v25-summary')){try{const s=await req('/api/stats'),box=document.createElement('div');box.className='v25-summary';box.innerHTML=[['今天',s.today],['7天',s.next7],['30天',s.next30],['逾期',s.overdue]].map(x=>`<button data-v25="stats"><b>${x[1]}</b><span>${x[0]}</span></button>`).join('');const controls=$('.controls');controls.parentNode.insertBefore(box,controls)}catch{}}
}
document.addEventListener('click',async e=>{const close=e.target.closest('[data-v25-close]');if(close)return $('#manageDialog').close();const b=e.target.closest('button');if(!b)return;try{const a=b.dataset.v25;if(a==='tools')return showTools();if(a==='stats')return showStats();if(a==='templates')return showTemplates();if(a==='trash')return showTrash();if(a==='logs')return showLogs();if(a==='series')return showSeries();if(a==='export')return exportData();if(a==='import')return importData();if(a==='calendar')return location.href='/api/calendar?days=365';if(a==='backup')return modal('最近自动备份','<p>每次保存前会自动保留上一版。点击恢复会覆盖当前数据。</p>','<button type="button" class="danger" data-backup-restore>恢复上一版</button>');if(a==='theme'){const cur=localStorage.getItem('family-hub-theme')||'system',next=cur==='system'?'dark':cur==='dark'?'light':'system';applyTheme(next);return alert(`主题已切换为 ${next}`)}if(a==='api')return apiDocs();if(b.dataset.template){await req('/api/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.template,startDate:new Date().toISOString().slice(0,10)})});location.reload()}if(b.dataset.restore){const d=await req('/api/ledger'),i=d.trash.findIndex(x=>x.id===b.dataset.restore);if(i>=0){const[x]=d.trash.splice(i,1);delete x.deletedAt;d.events.push(x);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload()}}if(b.dataset.seriesToggle){const d=await req('/api/ledger'),s=d.series.find(x=>x.id===b.dataset.seriesToggle);s.active=s.active===false;await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});showSeries()}if(b.dataset.seriesDelete){const d=await req('/api/ledger'),today=new Date().toISOString().slice(0,10);d.events=d.events.filter(x=>x.seriesId!==b.dataset.seriesDelete||x.date<today);d.series=d.series.filter(x=>x.id!==b.dataset.seriesDelete);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload()}if(b.hasAttribute('data-backup-restore')){if(confirm('确定恢复上一版数据？')){await req('/api/backup',{method:'POST'});location.reload()}}if(b.hasAttribute('data-import-save')){const data=JSON.parse($('#v25Import').value);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});location.reload()}}catch(err){alert(err.message)}});
applyTheme(localStorage.getItem('family-hub-theme')||'system');setInterval(enhance,600);enhance();
})();
