(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));let ledger=null,lastLoad=0;
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${title}</h2><button type="button" class="close" data-x26-close>×</button></header><div class="manage-body">${body}</div></div>`;d.showModal()}
async function load(force=false){if(!force&&ledger&&Date.now()-lastLoad<30000)return ledger;try{ledger=await req('/api/ledger');lastLoad=Date.now();return ledger}catch{return null}}
async function decorate(){const d=await load();if(!d)return;for(const c of $$('.event')){const x=(d.events||[]).find(v=>v.id===c.dataset.id);if(!x)continue;const line=$('.event-line',c);if(x.icon&&!$('.v26-logo',c)){const img=document.createElement('img');img.className='v26-logo';img.src=x.icon;img.alt='';img.loading='lazy';line.prepend(img)}if((x.attachments||[]).length&&!$('.v26-att',c)){const b=document.createElement('button');b.type='button';b.className='v26-att';b.textContent=`附件 ${x.attachments.length}`;b.dataset.x26Assets=x.id;$('.event-main',c).appendChild(b)}}}
async function backups(){const x=await req('/api/backup');modal('历史备份',`<div class="v25-list">${(x.items||[]).map(v=>`<div><b>${new Date(v.at).toLocaleString('zh-CN')}</b><small>${v.events} 条事项 · ${v.series} 条循环</small><button data-x26-restore="${v.slot}">恢复</button></div>`).join('')||'<p>暂无历史备份。产生保存操作后会自动保留最近 7 版。</p>'}</div>`)}
async function assets(id){const d=await load(true),x=(d.events||[]).find(v=>v.id===id);modal('查看附件',`<div class="v25-list">${(x.attachments||[]).map(a=>`<div><b>${a.name}</b><a href="${a.data}" target="_blank" rel="noopener" download="${a.name}">打开 / 保存</a></div>`).join('')||'<p>暂无附件</p>'}</div>`)}
function inject(){const box=$('.v25-tools');if(box&&!box.querySelector('[data-x26="backups"]'))box.insertAdjacentHTML('beforeend','<button data-x26="backups">历史备份</button>')}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-x26-close'))return $('#manageDialog').close();if(b.dataset.x26==='backups')return backups();if(b.dataset.x26Assets)return assets(b.dataset.x26Assets);if(b.dataset.x26Restore!==undefined&&confirm('确定恢复这个历史版本？当前数据会被覆盖。')){await req('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot:Number(b.dataset.x26Restore)})});location.reload()}}catch(err){alert(err.message)}});
setInterval(()=>{inject();decorate()},700);
})();