(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
let ledger=null,ledgerAt=0,pending=false;
async function data(force=false){if(!force&&ledger&&Date.now()-ledgerAt<30000)return ledger;ledger=await req('/api/ledger');ledgerAt=Date.now();return ledger}
async function topup(){const key='family-hub-topup-day-v28',day=new Date().toISOString().slice(0,10);if(localStorage.getItem(key)===day)return;try{const x=await req('/api/series');for(const s of x.series||[])if(s.active!==false)await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id,action:'topup'})});localStorage.setItem(key,day)}catch{}}
function paginate(){const timeline=$('.timeline');if(!timeline)return;const cards=$$('.event',timeline),limit=Number(timeline.dataset.limit||100);cards.forEach((c,i)=>c.hidden=i>=limit);let more=$('.rc-more',timeline);if(cards.length>limit){if(!more){more=document.createElement('button');more.type='button';more.className='ghost rc-more';more.textContent='加载更多';timeline.appendChild(more)}more.hidden=false}else if(more)more.hidden=true}
async function decorate(){pending=false;const d=await data().catch(()=>null);if(!d)return;const map=new Map((d.events||[]).map(x=>[x.id,x]));for(const card of $$('.event')){const x=map.get(card.dataset.id);if(!x)continue;const line=$('.event-line',card);if(x.icon&&line&&!$('.rc-logo',card)){const img=document.createElement('img');img.className='rc-logo';img.src=x.icon;img.alt='';img.loading='lazy';line.prepend(img)}if((x.attachments||[]).length&&!$('.rc-att',card)){const b=document.createElement('button');b.type='button';b.className='rc-att';b.textContent=`附件 ${x.attachments.length}`;b.dataset.rcAssets=x.id;$('.event-main',card)?.appendChild(b)}const menu=$('.row-menu',card);if(menu&&!menu.querySelector('[data-rc-edit-assets]'))menu.insertAdjacentHTML('beforeend','<button type="button" data-rc-edit-assets>附件 / Logo</button>')}
paginate()}
function schedule(){if(pending)return;pending=true;(window.requestAnimationFrame||setTimeout)(()=>decorate().catch(()=>{}))}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${title}</h2><button type="button" class="close" data-rc-feature-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;if(d.open)d.close();d.showModal()}
async function assets(id,edit=false){const d=await data(true),x=(d.events||[]).find(v=>v.id===id);if(!x)return;if(!edit)return modal('查看附件',`<div class="v25-list">${(x.attachments||[]).map(a=>`<div><b>${a.name}</b><a href="${a.data}" target="_blank" rel="noopener" download="${a.name}">打开 / 保存</a></div>`).join('')||'<p>暂无附件</p>'}</div>`);modal('附件与 Logo',`<p>附件支持图片或 PDF，单个不超过 160KB，每条最多 5 个。</p><label class="field full"><span>Logo 地址</span><input id="rcIcon" value="${x.icon||''}"></label><label class="field full"><span>新增附件</span><input id="rcFile" type="file" accept="image/*,.pdf"></label><div class="v25-list">${(x.attachments||[]).map(a=>`<div><b>${a.name}</b><button type="button" data-rc-remove-att="${a.id}" data-event-id="${id}">删除</button></div>`).join('')||'<p>暂无附件</p>'}</div>`,`<button type="button" class="ghost" data-rc-feature-close>取消</button><button type="button" class="primary" data-rc-save-asset="${id}">保存</button>`)}
async function saveAsset(id){const file=$('#rcFile')?.files?.[0],icon=$('#rcIcon')?.value||'';const body={eventId:id,icon};if(file){if(file.size>160000)throw Error('附件不能超过 160KB');body.file={name:file.name,type:file.type,data:await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}}await req('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});location.reload()}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b){schedule();return}try{if(b.classList.contains('rc-more')){const t=$('.timeline');t.dataset.limit=String(Number(t.dataset.limit||100)+100);return paginate()}if(b.hasAttribute('data-rc-feature-close'))return $('#manageDialog').close();if(b.dataset.rcAssets)return assets(b.dataset.rcAssets,false);if(b.hasAttribute('data-rc-edit-assets'))return assets(b.closest('.event')?.dataset.id,true);if(b.dataset.rcSaveAsset)return saveAsset(b.dataset.rcSaveAsset);if(b.dataset.rcRemoveAtt){await req(`/api/files?eventId=${encodeURIComponent(b.dataset.eventId)}&attachmentId=${encodeURIComponent(b.dataset.rcRemoveAtt)}`,{method:'DELETE'});ledger=null;return assets(b.dataset.eventId,true)}}catch(err){alert(err.message)}finally{setTimeout(schedule,0)}},true);
const app=$('#app');if(app&&'MutationObserver'in window){let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(schedule,30)}).observe(app,{childList:true,subtree:true})}
const style=document.createElement('style');style.textContent='.rc-logo{width:24px;height:24px;border-radius:7px;object-fit:cover;flex:0 0 auto}.rc-att{margin-top:4px;border:0;background:transparent;color:#806874;padding:0;font-size:10px;text-decoration:underline}.rc-more{display:block;margin:14px auto;padding:10px 22px}';document.head.appendChild(style);
topup();schedule();
})();