(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${title}</h2><button type="button" class="close" data-v26-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;d.showModal()}
async function topup(){const key='family-hub-topup-day-v2',day=new Date().toISOString().slice(0,10);if(localStorage.getItem(key)===day)return;try{const x=await req('/api/series');for(const s of x.series||[])if(s.active!==false)await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id,action:'topup'})});localStorage.setItem(key,day)}catch{}}
function paginate(){const timeline=$('.timeline');if(!timeline)return;const cards=$$('.event',timeline),limit=Number(timeline.dataset.limit||100);cards.forEach((c,i)=>c.hidden=i>=limit);let more=$('.v26-more',timeline);if(cards.length>limit){if(!more){more=document.createElement('button');more.type='button';more.className='ghost v26-more';more.textContent='加载更多';timeline.appendChild(more)}more.hidden=false}else if(more)more.hidden=true}
async function subscriptionStats(){const [d,r]=await Promise.all([req('/api/ledger'),req('/api/exchange-rates').catch(()=>({rates:{CNY:1}}))]),today=new Date().toISOString().slice(0,10),after=n=>{const x=new Date();x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)},sum=end=>(d.events||[]).filter(x=>x.type==='subscription'&&x.status!=='done'&&x.date>=today&&x.date<=end&&x.amount!=null).reduce((a,x)=>a+Number(x.amount)*(Number(r.rates?.[x.currency||'CNY'])||((x.currency||'CNY')==='CNY'?1:0)),0);modal('订阅统计',`<div class="v25-stats"><div><b>¥${sum(after(30)).toFixed(2)}</b><span>未来30天</span></div><div><b>¥${sum(after(90)).toFixed(2)}</b><span>未来季度</span></div><div><b>¥${sum(after(365)).toFixed(2)}</b><span>未来一年</span></div><div><b>${(d.events||[]).filter(x=>x.type==='subscription'&&x.status!=='done').length}</b><span>待续费订阅</span></div></div>`)}
async function seriesManager(){const x=await req('/api/series');modal('循环规则高级管理',`<p>系统每天首次进入时会自动补齐未来一年，无需手动操作。</p><div class="v25-list">${(x.series||[]).map(s=>`<div><b>${s.title}</b><small>${s.repeat} · ${s.startDate} 至 ${s.endDate}</small><button type="button" data-v26-series="${s.id}" data-op="toggle">${s.active===false?'恢复':'暂停'}</button><button type="button" data-v26-series="${s.id}" data-op="edit">编辑以后</button><button type="button" data-v26-series="${s.id}" data-op="delete">删除以后</button></div>`).join('')||'<p>暂无循环规则</p>'}</div>`)}
async function editSeries(id){const d=await req('/api/ledger'),s=(d.series||[]).find(x=>x.id===id);if(!s)return;modal('编辑本次及以后',`<div class="grid"><label class="field full"><span>标题</span><input id="v26Title" value="${s.title||''}"></label><label class="field"><span>起始日期</span><input id="v26From" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label class="field"><span>结束日期</span><input id="v26End" type="date" value="${s.endDate||''}"></label><label class="field"><span>周期</span><select id="v26Repeat">${['daily','weekly','monthly','quarterly','yearly','interval'].map(v=>`<option ${s.repeat===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>间隔天数</span><input id="v26Interval" type="number" min="1" value="${s.intervalDays||1}"></label></div>`,`<button type="button" class="ghost" data-v26-close>取消</button><button type="button" class="primary" data-v26-save-series="${id}">保存并重建未来实例</button>`)}
function addCardTools(){for(const card of $$('.event')){if(card.dataset.v26)return;card.dataset.v26='1';const menu=$('.row-menu',card);if(menu)menu.insertAdjacentHTML('beforeend','<button type="button" data-v26-asset>附件 / Logo</button>')}}
async function assets(card){const id=card.dataset.id,d=await req('/api/ledger'),x=d.events.find(v=>v.id===id);modal('附件与 Logo',`<p>Logo 可填写图片地址。附件支持图片或 PDF，单个不超过 160KB，每条最多 5 个。</p><label class="field full"><span>Logo 地址</span><input id="v26Icon" value="${x.icon||''}"></label><label class="field full"><span>新增附件</span><input id="v26File" type="file" accept="image/*,.pdf"></label><div class="v25-list">${(x.attachments||[]).map(a=>`<div><b>${a.name}</b><button type="button" data-v26-remove-att="${a.id}" data-event-id="${id}">删除</button></div>`).join('')||'<p>暂无附件</p>'}</div>`,`<button type="button" class="ghost" data-v26-close>取消</button><button type="button" class="primary" data-v26-save-asset="${id}">保存</button>`)}
async function saveAsset(id){const file=$('#v26File')?.files?.[0],icon=$('#v26Icon')?.value||'';let body={eventId:id,icon};if(file){if(file.size>160000)throw Error('附件不能超过 160KB');body.file={name:file.name,type:file.type,data:await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}}await req('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});location.reload()}
function sortableTypes(){const bar=$('.type-bar');if(!bar||bar.dataset.sortable)return;bar.dataset.sortable='1';for(const b of $$('.type-btn',bar)){if(['all','done'].includes(b.dataset.filter))continue;b.draggable=true;b.addEventListener('dragstart',()=>b.classList.add('dragging'));b.addEventListener('dragend',async()=>{b.classList.remove('dragging');const d=await req('/api/ledger');d.settings.typeOrder=$$('.type-btn',bar).map(x=>x.dataset.filter).filter(x=>x&&!['all','done'].includes(x));d.settings.types.sort((a,z)=>d.settings.typeOrder.indexOf(a.id)-d.settings.typeOrder.indexOf(z.id));await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)})})}bar.addEventListener('dragover',e=>{e.preventDefault();const moving=$('.dragging',bar);if(!moving)return;const target=e.target.closest('.type-btn');if(target&&target!==moving&&!['all','done'].includes(target.dataset.filter))bar.insertBefore(moving,target)})}
function injectTools(){const box=$('.v25-tools');if(box&&!box.dataset.v26){box.dataset.v26='1';box.insertAdjacentHTML('beforeend','<button type="button" data-v26="subscriptions">订阅统计</button><button type="button" data-v26="series">循环高级管理</button>')}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.matches('[data-v26-close]'))return $('#manageDialog').close();if(b.classList.contains('v26-more')){const t=$('.timeline');t.dataset.limit=String(Number(t.dataset.limit||100)+100);paginate();return}if(b.dataset.v26==='subscriptions')return subscriptionStats();if(b.dataset.v26==='series')return seriesManager();if(b.dataset.v26Series){const id=b.dataset.v26Series,op=b.dataset.op;if(op==='edit')return editSeries(id);if(op==='toggle'){await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'toggle'})});return seriesManager()}if(op==='delete'&&confirm('删除今天及以后的实例？')){await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'delete',scope:'future'})});location.reload()}}if(b.dataset.v26SaveSeries){await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.v26SaveSeries,action:'update',scope:'future',from:$('#v26From').value,patch:{title:$('#v26Title').value,endDate:$('#v26End').value,repeat:$('#v26Repeat').value,intervalDays:Number($('#v26Interval').value)||1}})});location.reload()}if(b.hasAttribute('data-v26-asset'))return assets(b.closest('.event'));if(b.dataset.v26SaveAsset)return saveAsset(b.dataset.v26SaveAsset);if(b.dataset.v26RemoveAtt){await req(`/api/files?eventId=${encodeURIComponent(b.dataset.eventId)}&attachmentId=${encodeURIComponent(b.dataset.v26RemoveAtt)}`,{method:'DELETE'});location.reload()}}catch(err){alert(err.message)}});
setInterval(()=>{injectTools();addCardTools();paginate();sortableTypes()},500);topup();
})();