(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
let ledger=null,loading=null;
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
async function data(force=false){if(force||!ledger)loading=req('/api/ledger').then(x=>(ledger=x));return loading||ledger}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-rules-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;if(d.open)d.close();d.showModal()}
function typeOptions(types,current){return(types||[]).map(x=>`<option value="${esc(x.id)}"${x.id===current?' selected':''}>${esc(x.name)}</option>`).join('')}
function repeatOptions(current){return[['daily','每天'],['weekly','每周'],['monthly','每月'],['quarterly','每季度'],['yearly','每年'],['interval','每隔 X 天']].map(([v,n])=>`<option value="${v}"${v===current?' selected':''}>${n}</option>`).join('')}
function openRule(event,series,d){const from=event.occurrenceDate||event.date;modal('编辑循环事项',`<div class="grid"><label class="field full"><span>修改范围</span><select id="ruleScope"><option value="single">仅本次</option><option value="future">本次及以后</option><option value="all">整个循环</option></select></label><label class="field full"><span>标题</span><input id="ruleTitle" value="${esc(series.title)}" maxlength="100"></label><label class="field"><span>类型</span><select id="ruleType">${typeOptions(d.settings?.types,series.type)}</select></label><label class="field"><span>周期</span><select id="ruleRepeat">${repeatOptions(series.repeat)}</select></label><label class="field"><span>起始日期</span><input id="ruleStart" type="date" value="${esc(series.startDate)}"></label><label class="field"><span>结束日期</span><input id="ruleEnd" type="date" value="${esc(series.endDate)}"></label><label class="field"><span>间隔天数</span><input id="ruleInterval" type="number" min="1" max="3650" value="${Number(series.intervalDays)||1}"></label><label class="field"><span>金额</span><input id="ruleAmount" type="number" min="0" step="0.01" value="${series.amount==null?'':esc(series.amount)}"></label><label class="field"><span>币种</span><input id="ruleCurrency" maxlength="8" value="${esc(series.currency||'CNY')}"></label><label class="field"><span>支付方式</span><input id="rulePayment" maxlength="50" value="${esc(series.payment||'')}"></label><label class="field full"><span>备注</span><textarea id="ruleNote" maxlength="1000">${esc(series.note||'')}</textarea></label><p class="full" style="font-size:12px;color:#8d7881">“仅本次”只打开当前实例编辑；另外两个范围会修改基础规则并自动重建对应的未完成事项。</p></div>`,`<button type="button" class="ghost" data-rules-close>取消</button><button type="button" class="primary" data-rule-save="${esc(series.id)}" data-event-id="${esc(event.id)}" data-from="${esc(from)}">保存</button>`)}
async function saveRule(b){const scope=$('#ruleScope').value;if(scope==='single'){const d=$('#manageDialog');d.close();const card=document.querySelector(`.event[data-id="${CSS.escape(b.dataset.eventId)}"]`);card?.dispatchEvent(new MouseEvent('click',{bubbles:true}));return}const start=$('#ruleStart').value,end=$('#ruleEnd').value;if(!start||!end)throw Error('请填写起始和结束日期');if(end<start)throw Error('结束日期不能早于起始日期');const repeat=$('#ruleRepeat').value,from=scope==='all'?start:b.dataset.from;const patch={title:$('#ruleTitle').value.trim(),type:$('#ruleType').value,repeat,startDate:scope==='future'?from:start,endDate:end,intervalDays:Number($('#ruleInterval').value)||1,amount:$('#ruleAmount').value===''?null:Math.round(Number($('#ruleAmount').value)*100)/100,currency:$('#ruleCurrency').value.trim().toUpperCase()||'CNY',payment:$('#rulePayment').value.trim(),note:$('#ruleNote').value.trim()};if(!patch.title)throw Error('标题不能为空');await req('/api/series',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.ruleSave,action:'update',scope,from,patch})});location.reload()}
document.addEventListener('click',async e=>{const edit=e.target.closest('button[data-action="edit"]');if(edit){const card=edit.closest('.event');if(!card)return;e.preventDefault();e.stopImmediatePropagation();try{const d=await data(true),event=(d.events||[]).find(x=>x.id===card.dataset.id);if(!event?.seriesId){card.dispatchEvent(new MouseEvent('click',{bubbles:true}));return}const series=(d.series||[]).find(x=>x.id===event.seriesId);if(!series)throw Error('循环基础规则不存在');openRule(event,series,d)}catch(err){alert(err.message)}return}const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-rules-close'))return $('#manageDialog').close();if(b.dataset.ruleSave)return await saveRule(b)}catch(err){alert(err.message)}},true);
})();