(()=>{
'use strict';
const VERSION='Beta v2.8.7 RC';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal rc-modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-rc-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;if(d.open)d.close();d.showModal()}
function syncVersion(){document.title=`Family Hub · 家庭事务中心 · ${VERSION}`;$$('.brand small,.login-card p').forEach(x=>x.textContent=`家庭事务中心 · ${VERSION}`)}
function top(){const el=$('.top');if(!el)return;$$('[data-action="export"],[data-v25],[data-v264],[data-v27-top]',el).forEach(x=>x.remove());const manage=el.querySelector('[data-action="manage"]');if(manage){manage.textContent='设置';manage.type='button'}const add=el.querySelector('[data-action="new"]');if(add&&!el.querySelector('[data-rc="stats"]')){const b=document.createElement('button');b.type='button';b.className='ghost compact';b.textContent='统计';b.dataset.rc='stats';el.insertBefore(b,manage||add)}const brand=el.querySelector('.brand');if(brand&&!brand.dataset.rc){brand.dataset.rc='1';brand.role='button';brand.tabIndex=0;brand.title='点击刷新';brand.style.cursor='pointer';brand.onclick=()=>location.reload();brand.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.reload()}}}syncVersion();$$('.v25-summary').forEach(x=>x.remove())}
async function stats(){const [s,d,r]=await Promise.all([req('/api/stats'),req('/api/ledger'),req('/api/exchange-rates').catch(()=>({rates:{CNY:1}}))]);const today=new Date().toISOString().slice(0,10),plus=n=>{const x=new Date();x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};const pending=(d.events||[]).filter(x=>!x.archived&&x.status!=='done'),subs=pending.filter(x=>x.type==='subscription'&&x.amount!=null);const sum=end=>subs.filter(x=>x.date>=today&&x.date<=end).reduce((n,x)=>n+Number(x.amount||0)*((x.currency||'CNY')==='CNY'?1:Number(r.rates?.[x.currency]||0)),0);const all=Number(s.total||0),done=Number(s.done||0),items=[['今天',s.today],['未来 7 天',s.next7],['未来 30 天',s.next30],['逾期',s.overdue],['全部事项',all],['已完成',done],['未完成',pending.length],['完成率',all?`${Math.round(done/all*100)}%`:'0%'],['30 天订阅',`¥${sum(plus(30)).toFixed(2)}`],['季度订阅',`¥${sum(plus(90)).toFixed(2)}`],['年度订阅',`¥${sum(plus(365)).toFixed(2)}`],['循环规则',(d.series||[]).length]];modal('统计',`<div class="rc-stats">${items.map(([k,v])=>`<div><b>${esc(v??0)}</b><span>${esc(k)}</span></div>`).join('')}</div>`)}
function settings(){modal('设置',`<div class="rc-groups"><section><h3>数据</h3><div class="rc-list"><button type="button" data-rc="export">导出 JSON <i>›</i></button><button type="button" data-rc="import">导入 JSON <i>›</i></button><button type="button" data-rc="calendar">导出日历 <i>›</i></button></div></section><section><h3>内容</h3><div class="rc-list"><button type="button" data-rc="types">类型管理 <i>›</i></button><button type="button" data-v25="templates">事项模板 <i>›</i></button></div></section><section><h3>连接</h3><div class="rc-list"><button type="button" data-rc="api">API 接口文档 <i>›</i></button></div></section><section><h3>外观</h3><div class="rc-list"><button type="button" data-rc="theme">切换主题 <i>›</i></button></div></section><section><h3>关于</h3><div class="rc-list"><div>Family Hub <small>${VERSION}</small></div><div>数据模型 <small>Version 8</small></div><div>数据安全 <small>保存前自动快照</small></div></div></section></div>`)}
async function types(){const d=await req('/api/ledger');modal('类型管理',`<div id="rcTypes">${(d.settings?.types||[]).map(x=>`<div class="rc-type" data-id="${esc(x.id)}"><input maxlength="20" value="${esc(x.name)}"><button type="button" data-rc-remove>删除</button></div>`).join('')}</div><button type="button" class="ghost" data-rc-add>＋ 新增类型</button>`,`<button type="button" class="ghost" data-rc-close>取消</button><button type="button" class="primary" data-rc-save-types>保存</button>`)}
async function saveTypes(){const d=await req('/api/ledger'),types=[];$$('#rcTypes .rc-type').forEach((row,i)=>{const name=$('input',row).value.trim();if(name)types.push({id:row.dataset.id||`type-${Date.now().toString(36)}-${i}`,name:name.slice(0,20)})});if(!types.length)throw Error('至少保留一个类型');const ids=new Set(types.map(x=>x.id)),fallback=types[0].id;(d.events||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});(d.series||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});d.settings=d.settings||{};d.settings.types=types;d.settings.typeOrder=types.map(x=>x.id);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload()}
function installStyle(){if($('#rc-style'))return;const s=document.createElement('style');s.id='rc-style';s.textContent='.rc-modal{max-width:620px}.rc-groups{display:grid;gap:16px}.rc-groups h3{margin:0 0 7px 8px;font-size:12px;color:#907b84}.rc-list{border:1px solid #eadfe3;border-radius:15px;overflow:hidden;background:#fff}.rc-list>button,.rc-list>div{width:100%;display:flex;justify-content:space-between;gap:10px;padding:13px 14px;border:0;border-bottom:1px solid #eee5e8;background:transparent;color:inherit;text-align:left}.rc-list>:last-child{border-bottom:0}.rc-list i{font-style:normal}.rc-list small{color:#9a858d}.rc-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.rc-stats div{border:1px solid #eadfe3;border-radius:13px;padding:12px;background:#fff}.rc-stats b{display:block;font-size:21px}.rc-stats span{font-size:11px;color:#8d7881}.rc-type{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;margin:8px 0}[data-theme="dark"] .rc-list,[data-theme="dark"] .rc-stats div{background:#242023;border-color:#3b3337}';document.head.appendChild(s)}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.action==='manage'){e.preventDefault();e.stopImmediatePropagation();return settings()}if(b.dataset.rc==='stats')return stats();if(b.hasAttribute('data-rc-close'))return $('#manageDialog').close();if(b.dataset.rc==='export'){const d=await req('/api/ledger');return download(`family-hub-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(d,null,2))}if(b.dataset.rc==='import'){const text=prompt('粘贴完整 JSON');if(text){await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(JSON.parse(text))});location.reload()}return}if(b.dataset.rc==='calendar'){location.href='/api/calendar?days=365';return}if(b.dataset.rc==='types')return types();if(b.dataset.rc==='api'){location.href='/api.html';return}if(b.dataset.rc==='theme'){const cur=localStorage.getItem('family-hub-theme')||'system',next=cur==='system'?'dark':cur==='dark'?'light':'system';localStorage.setItem('family-hub-theme',next);if(next==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=next;location.reload();return}if(b.hasAttribute('data-rc-add')){$('#rcTypes').insertAdjacentHTML('beforeend','<div class="rc-type"><input maxlength="20" value="新类型"><button type="button" data-rc-remove>删除</button></div>');return}if(b.hasAttribute('data-rc-remove')){b.closest('.rc-type').remove();return}if(b.hasAttribute('data-rc-save-types'))return saveTypes()}catch(err){alert(err.message)}},true);
installStyle();syncVersion();document.addEventListener('DOMContentLoaded',()=>{top();syncVersion()},{once:true});let tries=0;(function ready(){top();if(!$('.top')&&++tries<40)setTimeout(ready,50)})();
})();