(()=>{
'use strict';
const VERSION='Beta v2.8.1 RC';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s)),esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-rc-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;if(d.open)d.close();d.showModal()}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function showStats(){const [s,d,r]=await Promise.all([req('/api/stats'),req('/api/ledger'),req('/api/exchange-rates').catch(()=>({rates:{CNY:1}}))]);const today=new Date().toISOString().slice(0,10),after=n=>{const x=new Date();x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)},pending=(d.events||[]).filter(x=>!x.archived&&x.status!=='done'),subs=pending.filter(x=>x.type==='subscription'&&x.amount!=null),sum=end=>subs.filter(x=>x.date>=today&&x.date<=end).reduce((n,x)=>n+Number(x.amount||0)*((x.currency||'CNY')==='CNY'?1:Number(r.rates?.[x.currency]||0)),0),all=Number(s.total||0),done=Number(s.done||0),rate=all?Math.round(done/all*100):0;modal('统计',`<div class="v25-stats">${[['今天',s.today],['未来 7 天',s.next7],['未来 30 天',s.next30],['逾期',s.overdue],['全部事项',all],['已完成',done],['未完成',pending.length],['完成率',rate+'%'],['30 天订阅','¥'+sum(after(30)).toFixed(2)],['季度订阅','¥'+sum(after(90)).toFixed(2)],['年度订阅','¥'+sum(after(365)).toFixed(2)],['待续费订阅',subs.length]].map(x=>`<div><b>${esc(x[1]??0)}</b><span>${esc(x[0])}</span></div>`).join('')}</div>`)}
function settings(){modal('设置',`<div class="v27-groups"><section><h3>数据</h3><div class="v27-list"><button type="button" data-rc="export">导出数据</button><button type="button" data-rc="import">导入 JSON</button><button type="button" data-rc="restore">恢复最近备份</button><button type="button" data-rc="calendar">导出日历</button></div></section><section><h3>内容</h3><div class="v27-list"><button type="button" data-rc="types">类型管理</button><button type="button" data-v25="templates">事项模板</button><button type="button" data-rc="trash">回收站</button></div></section><section><h3>连接</h3><div class="v27-list"><button type="button" data-rc="api">API 接口文档</button></div></section><section><h3>外观</h3><div class="v27-list"><button type="button" data-rc="theme">主题</button></div></section><section><h3>关于</h3><div class="v27-list"><button type="button" data-rc="about">Family Hub · ${VERSION}</button></div></section></div>`)}
async function types(){const d=await req('/api/ledger'),rows=(d.settings?.types||[]).map(x=>`<div class="type-row" data-id="${esc(x.id)}"><input value="${esc(x.name)}" maxlength="20"><button type="button" data-remove-type>删除</button></div>`).join('');modal('类型管理',`<div id="rcTypeRows">${rows}</div><button type="button" data-add-type>＋ 新增类型</button>`,`<button type="button" data-rc-close>取消</button><button type="button" data-save-types>保存</button>`)}
async function saveTypes(){const d=await req('/api/ledger'),types=[];$$('#rcTypeRows .type-row').forEach((row,i)=>{const name=$('input',row).value.trim();if(name)types.push({id:row.dataset.id||`type-${Date.now().toString(36)}-${i}`,name})});if(!types.length)throw Error('至少保留一个类型');const ids=new Set(types.map(x=>x.id)),fallback=types[0].id;(d.events||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});(d.series||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});d.settings.types=types;d.settings.typeOrder=types.map(x=>x.id);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload()}
async function exportData(){const d=await req('/api/ledger'),f=(prompt('输入导出格式：json / csv / markdown','json')||'json').toLowerCase();if(f==='csv'){const rows=[['标题','类型','日期','状态','金额','币种','支付方式','备注'],...(d.events||[]).map(x=>[x.title,x.type,x.date,x.status,x.amount??'',x.currency,x.payment,x.note])];return download('family-hub.csv',rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}if(f==='markdown')return download('family-hub.md',['# Family Hub','',...(d.events||[]).map(x=>`- [${x.status==='done'?'x':' '}] ${x.date} ${x.title}`)].join('\n'),'text/markdown');download('family-hub.json',JSON.stringify(d,null,2),'application/json')}
function importData(){modal('导入 JSON','<textarea id="rcImport" style="width:100%;min-height:240px"></textarea>','<button type="button" data-rc-close>取消</button><button type="button" data-import-save>导入并覆盖</button>')}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.action==='manage'){e.preventDefault();e.stopImmediatePropagation();return settings()}if(b.dataset.rc==='stats')return showStats();if(b.hasAttribute('data-rc-close'))return $('#manageDialog').close();const a=b.dataset.rc;if(a==='export')return exportData();if(a==='import')return importData();if(a==='restore'){if(confirm('确定恢复最近一次备份？')){await req('/api/backup',{method:'POST'});location.reload()}return}if(a==='calendar')return location.href='/api/calendar?days=365';if(a==='types')return types();if(a==='api')return location.href='/api.html';if(a==='theme'){const cur=localStorage.getItem('family-hub-theme')||'system',next=cur==='system'?'dark':cur==='dark'?'light':'system';localStorage.setItem('family-hub-theme',next);location.reload();return}if(a==='about')return modal('关于',`<p>${VERSION}</p><p>数据模型 Version 8</p>`);if(b.hasAttribute('data-add-type')){$('#rcTypeRows').insertAdjacentHTML('beforeend','<div class="type-row"><input value="新类型" maxlength="20"><button type="button" data-remove-type>删除</button></div>');return}if(b.hasAttribute('data-remove-type'))return b.closest('.type-row').remove();if(b.hasAttribute('data-save-types'))return saveTypes();if(b.hasAttribute('data-import-save')){const d=JSON.parse($('#rcImport').value);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload()}}catch(err){alert(err.message)}},true);
})();