(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
let templates=[],types=[];
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-tpl-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;d.showModal()}
function typeOptions(selected){return types.map(x=>`<option value="${esc(x.id)}"${x.id===selected?' selected':''}>${esc(x.name)}</option>`).join('')}
function itemRow(x={}){return `<div class="tpl-item"><label class="field"><span>事项标题</span><input data-ti="title" value="${esc(x.title||'')}" maxlength="100"></label><label class="field"><span>类型</span><select data-ti="type">${typeOptions(x.type||types[0]?.id)}</select></label><label class="field"><span>距起始日</span><input data-ti="offsetDays" type="number" min="0" max="36500" value="${Number(x.offsetDays)||0}"></label><label class="field"><span>金额</span><input data-ti="amount" type="number" min="0" step="0.01" value="${x.amount==null?'':Number(x.amount).toFixed(2)}"></label><label class="field"><span>币种</span><input data-ti="currency" value="${esc(x.currency||'CNY')}" maxlength="8"></label><label class="field"><span>支付方式</span><input data-ti="payment" value="${esc(x.payment||'')}" maxlength="50"></label><label class="field full"><span>备注</span><input data-ti="note" value="${esc(x.note||'')}" maxlength="1000"></label><button type="button" class="danger tpl-remove">删除这一项</button></div>`}
async function load(){const [t,d]=await Promise.all([req('/api/templates'),req('/api/ledger')]);templates=t.templates||[];types=d.settings?.types||[]}
async function list(){await load();modal('事项模板',`<div class="tpl-head"><p>模板用于按一个起始日期批量创建多条事项。</p><button type="button" class="primary" data-tpl-new>＋ 新建模板</button></div><div class="v25-list">${templates.map(t=>`<div><b>${esc(t.name)}${t.builtIn?' <small>内置</small>':''}</b><small>${(t.items||[]).length} 个事项</small><button type="button" data-tpl-use="${esc(t.id)}">使用</button>${t.builtIn?'':`<button type="button" data-tpl-edit="${esc(t.id)}">编辑</button><button type="button" class="danger" data-tpl-delete="${esc(t.id)}">删除</button>`}</div>`).join('')||'<p>暂无模板</p>'}</div>`)}
function edit(id=''){const t=templates.find(x=>x.id===id)||{name:'',items:[{}]};modal(id?'编辑模板':'新建模板',`<label class="field full"><span>模板名称</span><input id="tplName" value="${esc(t.name)}" maxlength="40"></label><div id="tplItems">${(t.items||[{}]).map(itemRow).join('')}</div><button type="button" class="ghost" data-tpl-add>＋ 添加事项</button>`,`<button type="button" class="ghost" data-tpl-close>取消</button><button type="button" class="primary" data-tpl-save="${esc(id)}">保存模板</button>`)}
function collectItems(){return Array.from(document.querySelectorAll('.tpl-item')).map(row=>{const get=n=>row.querySelector(`[data-ti="${n}"]`)?.value??'';return{title:get('title').trim(),type:get('type'),offsetDays:Number(get('offsetDays'))||0,amount:get('amount')===''?null:Number(get('amount')),currency:get('currency').trim().toUpperCase()||'CNY',payment:get('payment').trim(),note:get('note').trim()}}).filter(x=>x.title)}
function apply(id){const t=templates.find(x=>x.id===id);modal(`使用“${t?.name||'模板'}”`,`<p>系统会以起始日期为基准，按照模板中每项的偏移天数创建独立事项。</p><label class="field full"><span>起始日期</span><input id="tplStart" type="date" value="${new Date().toISOString().slice(0,10)}"></label>`,`<button type="button" class="ghost" data-tpl-close>取消</button><button type="button" class="primary" data-tpl-apply="${esc(id)}">确认创建</button>`)}
function bindTitle(){const brand=$('.brand');if(brand&&!brand.dataset.refresh){brand.dataset.refresh='1';brand.title='点击刷新当前页面';brand.style.cursor='pointer';brand.setAttribute('role','button');brand.setAttribute('tabindex','0');brand.addEventListener('click',()=>location.reload());brand.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.reload()}})}}
document.addEventListener('click',async e=>{const templateEntry=e.target.closest('[data-v25="templates"]');if(templateEntry){e.preventDefault();e.stopImmediatePropagation();try{await list()}catch(err){alert(err.message)}return}},true);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-tpl-close'))return $('#manageDialog').close();if(b.hasAttribute('data-tpl-new'))return edit();if(b.dataset.tplEdit)return edit(b.dataset.tplEdit);if(b.dataset.tplUse)return apply(b.dataset.tplUse);if(b.hasAttribute('data-tpl-add'))return $('#tplItems').insertAdjacentHTML('beforeend',itemRow({}));if(b.classList.contains('tpl-remove')){if(document.querySelectorAll('.tpl-item').length<=1)return alert('模板至少保留一个事项');b.closest('.tpl-item').remove();return}if(b.dataset.tplSave!==undefined){const name=$('#tplName').value.trim(),items=collectItems();if(!name)return alert('请输入模板名称');if(!items.length)return alert('模板至少需要一个有效事项');await req('/api/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',id:b.dataset.tplSave||undefined,name,items})});return list()}if(b.dataset.tplApply){await req('/api/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'apply',id:b.dataset.tplApply,startDate:$('#tplStart').value})});location.reload();return}if(b.dataset.tplDelete){if(!confirm('确定删除这个个人模板？'))return;await req(`/api/templates?id=${encodeURIComponent(b.dataset.tplDelete)}`,{method:'DELETE'});return list()}}catch(err){alert(err.message)}});
document.addEventListener('input',e=>{if(e.target.matches('[data-ti="currency"]'))e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'')});
setInterval(bindTitle,500);bindTitle();
})();