(function(){
'use strict';
const VERSION='Beta v2.7.0';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>{const e=document.createElement('i');e.textContent=v==null?'':String(v);return e.innerHTML};
async function req(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.error||`请求失败 ${r.status}`);return j}
function modal(title,body,footer=''){const d=$('#manageDialog'),f=$('#manageForm');f.innerHTML=`<div class="modal v27-modal"><header><h2>${esc(title)}</h2><button type="button" class="close" data-v27-close>×</button></header><div class="manage-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</div>`;if(d.open)d.close();d.showModal()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function installStyle(){if($('#v27-style'))return;const s=document.createElement('style');s.id='v27-style';s.textContent=`
.v27-modal{max-width:620px}.v27-groups{display:grid;gap:16px}.v27-group h3{font-size:12px;color:#907b84;margin:0 0 7px 8px}.v27-list{overflow:hidden;border:1px solid #eadfe3;border-radius:15px;background:#fff}.v27-row{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px;border:0;border-bottom:1px solid #eee5e8;background:transparent;padding:14px 15px;text-align:left;color:inherit}.v27-row:last-child{border-bottom:0}.v27-row span{display:grid;gap:2px}.v27-row small{font-size:10.5px;color:#9a858d}.v27-row i{font-style:normal;color:#b09da5}.v27-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.v27-stat{border:1px solid #eadfe3;border-radius:13px;padding:12px;background:#fff}.v27-stat b{display:block;font-size:21px;line-height:1.15}.v27-stat span{font-size:11px;color:#8d7881}.v27-section-title{font-size:13px;margin:18px 0 8px}.v27-type-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;margin:8px 0}.v27-type-row input{width:100%}.v27-import{width:100%;min-height:240px}.brand{user-select:none}.brand:active{opacity:.65}[data-theme="dark"] .v27-list,[data-theme="dark"] .v27-stat{background:#242023;border-color:#3b3337}[data-theme="dark"] .v27-row{border-color:#3b3337}@media(max-width:520px){.v27-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.v27-row{padding:13px 12px}}
`;document.head.appendChild(s)}
function ensureTop(){const top=$('.top');if(!top)return;$$('[data-action="export"],[data-v25="tools"],[data-v264="stats"],[data-v27-top]',top).forEach(x=>x.remove());const manage=top.querySelector('[data-action="manage"]');if(manage){manage.textContent='设置';manage.type='button'}const add=top.querySelector('[data-action="new"]');if(add&&!top.querySelector('[data-v27-top="stats"]')){const b=document.createElement('button');b.type='button';b.className='ghost compact';b.textContent='统计';b.dataset.v27Top='stats';top.insertBefore(b,manage||add)}const brand=$('.brand');if(brand&&!brand.dataset.v27Refresh){brand.dataset.v27Refresh='1';brand.title='点击刷新并同步';brand.style.cursor='pointer';brand.setAttribute('role','button');brand.setAttribute('tabindex','0');brand.addEventListener('click',()=>location.reload());brand.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.reload()}})}}
async function stats(){const [s,d,r]=await Promise.all([req('/api/stats'),req('/api/ledger'),req('/api/exchange-rates').catch(()=>({rates:{CNY:1}}))]);const today=new Date().toISOString().slice(0,10),dateAfter=n=>{const x=new Date();x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};const pending=(d.events||[]).filter(x=>!x.archived&&x.status!=='done'),subs=pending.filter(x=>x.type==='subscription'&&x.amount!=null);const total=(end)=>subs.filter(x=>x.date>=today&&x.date<=end).reduce((n,x)=>{const c=x.currency||'CNY',rate=c==='CNY'?1:Number(r.rates?.[c]||0);return n+Number(x.amount||0)*rate},0);const all=Math.max(0,Number(s.total||0)),done=Math.max(0,Number(s.done||0)),rate=all?Math.round(done/all*100):0,typeMap=new Map((d.settings?.types||[]).map(x=>[x.id,x.name])),counts={};pending.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);const items=[['今天',s.today],['未来 7 天',s.next7],['未来 30 天',s.next30],['逾期',s.overdue],['全部事项',all],['已完成',done],['未完成',pending.length],['完成率',`${rate}%`],['30 天订阅',`¥${total(dateAfter(30)).toFixed(2)}`],['季度订阅',`¥${total(dateAfter(90)).toFixed(2)}`],['年度订阅',`¥${total(dateAfter(365)).toFixed(2)}`],['待续费订阅',subs.length],['循环规则',(d.series||[]).length],['进行中循环',(d.series||[]).filter(x=>x.active!==false).length],['附件',(d.events||[]).reduce((n,x)=>n+(x.attachments||[]).length,0)],['个人模板',(d.templates||[]).length]];const types=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([id,n])=>`<button type="button" class="v27-stat" data-v27-filter="${esc(id)}"><b>${n}</b><span>${esc(typeMap.get(id)||id)}</span></button>`).join('');modal('统计',`<div class="v27-stats">${items.map(x=>`<div class="v27-stat"><b>${esc(x[1]??0)}</b><span>${esc(x[0])}</span></div>`).join('')}</div>${types?`<h3 class="v27-section-title">按类型</h3><div class="v27-stats">${types}</div>`:''}`)}
function settings(){modal('设置',`<div class="v27-groups">
<section class="v27-group"><h3>数据</h3><div class="v27-list"><button type="button" class="v27-row" data-v27="export"><span>导出数据<small>JSON、CSV 或 Markdown</small></span><i>›</i></button><button type="button" class="v27-row" data-v27="import"><span>导入 JSON<small>覆盖前会自动保留备份</small></span><i>›</i></button><button type="button" class="v27-row" data-v27="restore"><span>恢复最近备份<small>恢复上一次保存前的数据</small></span><i>›</i></button><button type="button" class="v27-row" data-v27="calendar"><span>导出日历<small>生成未来一年的 ICS 文件</small></span><i>›</i></button></div></section>
<section class="v27-group"><h3>内容</h3><div class="v27-list"><button type="button" class="v27-row" data-v27="types"><span>类型管理<small>新增、改名、删除和排序</small></span><i>›</i></button><button type="button" class="v27-row" data-v25="templates"><span>事项模板<small>新增、编辑、删除和使用模板</small></span><i>›</i></button><button type="button" class="v27-row" data-v27="trash"><span>回收站<small>恢复最近 30 天删除的事项</small></span><i>›</i></button></div></section>
<section class="v27-group"><h3>连接</h3><div class="v27-list"><button type="button" class="v27-row" data-v27="api"><span>API 接口文档<small>查看鉴权、字段和调用示例</small></span><i>›</i></button></div></section>
<section class="v27-group"><h3>外观</h3><div class="v27-list"><button type="button" class="v27-row" data-v27="theme"><span>主题<small>跟随系统、浅色或深色</small></span><i>›</i></button></div></section>
<section class="v27-group"><h3>关于</h3><div class="v27-list"><button type="button" class="v27-row" data-v27="about"><span>Family Hub<small>${VERSION}</small></span><i>›</i></button></div></section>
</div>`)}
async function types(){const d=await req('/api/ledger'),rows=(d.settings?.types||[]).map(x=>`<div class="v27-type-row" data-id="${esc(x.id)}"><input value="${esc(x.name)}" maxlength="20"><button type="button" data-v27-remove-type>删除</button></div>`).join('');modal('类型管理',`<div id="v27TypeRows">${rows}</div><button type="button" class="ghost" data-v27-add-type>＋ 新增类型</button>`,`<button type="button" class="ghost" data-v27-close>取消</button><button type="button" class="primary" data-v27-save-types>保存</button>`)}
async function saveTypes(){const d=await req('/api/ledger'),used=new Set(),types=[];$$('#v27TypeRows .v27-type-row').forEach((row,i)=>{const name=$('input',row).value.trim();if(!name)return;let id=row.dataset.id||`type-${Date.now().toString(36)}-${i}`;while(used.has(id))id+=`-${i}`;used.add(id);types.push({id,name:name.slice(0,20)})});if(!types.length)throw Error('至少保留一个类型');const ids=new Set(types.map(x=>x.id)),fallback=types[0].id;(d.events||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});(d.series||[]).forEach(x=>{if(!ids.has(x.type))x.type=fallback});d.settings=d.settings||{};d.settings.types=types;d.settings.typeOrder=types.map(x=>x.id);const saved=await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!Array.isArray(saved.settings?.types)||saved.settings.types.length!==types.length)throw Error('保存后校验失败');location.reload()}
async function exportData(){const d=await req('/api/ledger'),format=(prompt('输入导出格式：json / csv / markdown','json')||'json').toLowerCase();if(format==='csv'){const rows=[['标题','类型','日期','状态','金额','币种','支付方式','备注'],...(d.events||[]).map(x=>[x.title,x.type,x.date,x.status,x.amount??'',x.currency,x.payment,x.note])];return download('family-hub.csv',rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}if(format==='markdown')return download('family-hub.md',['# Family Hub','',...(d.events||[]).map(x=>`- [${x.status==='done'?'x':' '}] ${x.date} ${x.title}${x.note?` — ${x.note}`:''}`)].join('\n'),'text/markdown');download('family-hub.json',JSON.stringify(d,null,2),'application/json')}
function importData(){modal('导入 JSON','<textarea id="v27Import" class="v27-import" placeholder="粘贴完整的 Family Hub JSON 数据"></textarea>','<button type="button" class="ghost" data-v27-close>取消</button><button type="button" class="primary" data-v27-import-save>导入并覆盖</button>')}
async function trash(){const d=await req('/api/ledger'),now=Date.now(),list=(d.trash||[]).filter(x=>!x.deletedAt||now-new Date(x.deletedAt).getTime()<30*86400000);modal('回收站',`<div class="v25-list">${list.length?list.map(x=>`<div><b>${esc(x.title)}</b><small>${esc(x.date||'')}</small><button type="button" data-v27-restore-item="${esc(x.id)}">恢复</button></div>`).join(''):'<p>回收站为空</p>'}</div>`)}
function theme(){const cur=localStorage.getItem('family-hub-theme')||'system';modal('主题',`<div class="v27-list">${[['system','跟随系统'],['light','浅色'],['dark','深色']].map(x=>`<button type="button" class="v27-row" data-v27-theme="${x[0]}"><span>${x[1]}<small>${cur===x[0]?'当前使用':''}</small></span><i>${cur===x[0]?'✓':'›'}</i></button>`).join('')}</div>`)}
function applyTheme(v){localStorage.setItem('family-hub-theme',v);document.documentElement.dataset.theme=v;if(v==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=v;location.reload()}
function about(){modal('关于',`<div class="v27-list"><div class="v27-row"><span>版本<small>${VERSION}</small></span></div><div class="v27-row"><span>数据模型<small>Version 8</small></span></div><div class="v27-row"><span>循环维护<small>每日自动补齐未来一年</small></span></div><div class="v27-row"><span>自动备份<small>每次保存前保留上一版</small></span></div></div>`)}
function removeOldMenus(){const f=$('#manageForm');if(!f)return;$$('[data-v25="tools"],[data-v264],[data-v26="topup"]',f).forEach(x=>x.remove())}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.action==='manage'){e.preventDefault();e.stopImmediatePropagation();settings();return}if(b.dataset.v27Top==='stats'){e.preventDefault();e.stopImmediatePropagation();stats();return}if(b.hasAttribute('data-v27-close'))return $('#manageDialog').close();const a=b.dataset.v27;if(a==='export')return exportData();if(a==='import')return importData();if(a==='restore'){if(confirm('确定恢复最近一次备份？当前数据会被覆盖。')){await req('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.reload()}return}if(a==='calendar'){location.href='/api/calendar?days=365';return}if(a==='types')return types();if(a==='trash')return trash();if(a==='api'){location.href='/api.html';return}if(a==='theme')return theme();if(a==='about')return about();if(b.hasAttribute('data-v27-add-type')){$('#v27TypeRows').insertAdjacentHTML('beforeend',`<div class="v27-type-row"><input value="新类型" maxlength="20"><button type="button" data-v27-remove-type>删除</button></div>`);return}if(b.hasAttribute('data-v27-remove-type')){b.closest('.v27-type-row').remove();return}if(b.hasAttribute('data-v27-save-types'))return saveTypes();if(b.hasAttribute('data-v27-import-save')){const data=JSON.parse($('#v27Import').value);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});location.reload();return}if(b.dataset.v27RestoreItem){const d=await req('/api/ledger'),i=(d.trash||[]).findIndex(x=>x.id===b.dataset.v27RestoreItem);if(i<0)throw Error('事项不存在');const[x]=d.trash.splice(i,1);delete x.deletedAt;d.events.push(x);await req('/api/ledger',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload();return}if(b.dataset.v27Theme)return applyTheme(b.dataset.v27Theme);if(b.dataset.v27Filter){$('#manageDialog').close();const chip=$(`.type-btn[data-filter="${CSS.escape(b.dataset.v27Filter)}"]`);if(chip)chip.click();return}}catch(err){alert(err.message)}},true);
installStyle();let n=0;(function tick(){ensureTop();removeOldMenus();document.title=`Family Hub · 家庭事务中心 · ${VERSION}`;document.querySelectorAll('.brand small,.login-card p').forEach(x=>x.textContent=`家庭事务中心 · ${VERSION}`);if(++n<480)setTimeout(tick,250)})();
})();