import { json, readJson, requireAccess } from "../../_lib.js";
import { readData, saveData } from "../../_storage.js";

const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const parse=v=>new Date(`${v}T12:00:00`);
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
const add=(d,r,n,anchor)=>{const x=new Date(d);if(r==="daily")x.setDate(x.getDate()+1);else if(r==="weekly")x.setDate(x.getDate()+7);else if(r==="interval")x.setDate(x.getDate()+Math.max(1,n||1));else{const m=r==="quarterly"?3:r==="yearly"?12:1;x.setDate(1);x.setMonth(x.getMonth()+m);x.setDate(Math.min(anchor,new Date(x.getFullYear(),x.getMonth()+1,0).getDate()))}return x};
function generate(series,from,to,existing){const out=[],seen=new Set(existing.filter(x=>x.seriesId===series.id).map(x=>x.occurrenceDate||x.date)),anchor=parse(series.startDate).getDate();let d=parse(series.startDate);while(d<parse(from))d=add(d,series.repeat,series.intervalDays,anchor);while(d<=parse(to)&&out.length<1000){const date=iso(d);if(!seen.has(date))out.push({id:uid("evt"),title:series.title,type:series.type,date,occurrenceDate:date,seriesId:series.id,calendar:series.calendar||"solar",lunarMonth:series.lunarMonth||null,lunarDay:series.lunarDay||null,status:"pending",amount:series.amount??null,currency:series.currency||"CNY",payment:series.payment||"",note:series.note||"",icon:series.icon||"",attachments:[],archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});d=add(d,series.repeat,series.intervalDays,anchor)}return out}
const log=(d,a,s,detail="")=>{d.logs=d.logs||[];d.logs.push({id:uid("log"),action:a,itemId:s?.id||"",title:s?.title||"",detail,at:new Date().toISOString()});d.logs=d.logs.slice(-500)};
export async function onRequestGet(context){const a=await requireAccess(context);if(a.response)return a.response;const d=await readData();return json({series:d.series||[]})}
export async function onRequestPost(context){const a=await requireAccess(context);if(a.response)return a.response;try{const body=await readJson(context.request),d=await readData(),action=String(body.action||"topup"),id=String(body.id||""),s=(d.series||[]).find(x=>x.id===id);if(!s)return json({error:"循环规则不存在"},404);const today=iso(new Date()),until=body.until||(()=>{const x=new Date();x.setFullYear(x.getFullYear()+1);return iso(x)})();if(action==="topup"){const list=generate(s,today,until,d.events||[]);d.events.push(...list);log(d,"series.topup",s,`补齐 ${list.length} 条`)}else if(action==="toggle"){s.active=s.active===false;log(d,s.active?"series.resume":"series.pause",s)}else if(action==="update"){const from=body.from||today,scope=body.scope||"future",patch=body.patch||{};Object.assign(s,patch,{updatedAt:new Date().toISOString()});if(scope!=="single"){d.events=(d.events||[]).filter(x=>x.seriesId!==id||x.date<from||x.status==="done");const list=generate(s,from,s.endDate||until,d.events);d.events.push(...list)}log(d,"series.update",s,scope)}else if(action==="delete"){const from=body.from||today,scope=body.scope||"future";if(scope==="all"){d.events=(d.events||[]).filter(x=>x.seriesId!==id);d.series=d.series.filter(x=>x.id!==id)}else{d.events=(d.events||[]).filter(x=>x.seriesId!==id||x.date<from);s.active=false;s.endDate=from}log(d,"series.delete",s,scope)}else return json({error:"不支持的操作"},400);d.updatedAt=new Date().toISOString();await saveData(d);return json(d)}catch(e){return json({error:e.message||"操作失败"},400)}}
