const encoder = new TextEncoder();
export const COOKIE_NAME = "__Host-homeledger_session";
export const SESSION_MAX_AGE = 60 * 60 * 24 * 30;
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers}})}
export function getSecrets(context){const env=context?.env||{};const adminPassword=env.ADMIN_PASSWORD||globalThis.ADMIN_PASSWORD;const sessionSecret=env.SESSION_SECRET||globalThis.SESSION_SECRET;if(!adminPassword||!sessionSecret)throw Error("ADMIN_PASSWORD and SESSION_SECRET must be configured");return{adminPassword:String(adminPassword),sessionSecret:String(sessionSecret),apiKey:String(env.API_KEY||globalThis.API_KEY||"")}}
export function parseCookies(request){return(request.headers.get("Cookie")||"").split(";").reduce((r,x)=>{const i=x.indexOf("=");if(i>0)r[x.slice(0,i).trim()]=x.slice(i+1).trim();return r},{})}
function base64url(bytes){let s="";for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function hmac(value,secret){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return base64url(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
function safeEqual(a,b){if(typeof a!=="string"||typeof b!=="string")return false;let d=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)d|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return d===0}
async function digest(value){return base64url(await crypto.subtle.digest("SHA-256",encoder.encode(value)))}
export async function passwordMatches(value,expected){return safeEqual(await digest(value),await digest(expected))}
export async function createSession(secret){const issued=Math.floor(Date.now()/1000),nonce=base64url(crypto.getRandomValues(new Uint8Array(18))),unsigned=`${issued}.${nonce}`;return`${unsigned}.${await hmac(unsigned,secret)}`}
export async function isAuthenticated(request,secret){const token=parseCookies(request)[COOKIE_NAME];if(!token)return false;const[issued,nonce,signature,...extra]=token.split("."),now=Math.floor(Date.now()/1000);return!extra.length&&/^\d{10}$/.test(issued)&&/^[A-Za-z0-9_-]{16,}$/.test(nonce)&&Number(issued)<=now+60&&now-Number(issued)<=SESSION_MAX_AGE&&safeEqual(signature,await hmac(`${issued}.${nonce}`,secret))}
export function sessionCookie(value){return`${COOKIE_NAME}=${value}; Path=/; Max-Age=${SESSION_MAX_AGE}; HttpOnly; Secure; SameSite=Strict`}
export function clearSessionCookie(){return`${COOKIE_NAME}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict`}
export async function requireAuth(context){try{const{sessionSecret}=getSecrets(context);return await isAuthenticated(context.request,sessionSecret)?{sessionSecret}:{response:json({error:"Unauthorized"},401)}}catch{return{response:json({error:"Server authentication is not configured"},503)}}}
export async function requireAccess(context){try{const secrets=getSecrets(context),request=context.request;const supplied=request.headers.get("X-API-Key")||(request.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(secrets.apiKey&&safeEqual(supplied,secrets.apiKey))return{mode:"api"};if(await isAuthenticated(request,secrets.sessionSecret))return{mode:"session"};return{response:json({error:"Unauthorized"},401)}}catch{return{response:json({error:"Server authentication is not configured"},503)}}}
export async function readJson(request){const text=await request.text();if(text.length>2000000)throw Error("Request body is too large");try{const value=JSON.parse(text||"{}");if(!value||typeof value!=="object"||Array.isArray(value))throw Error();return value}catch{throw Error("Invalid JSON request body")}}
