const $ = (s, r = document) => r.querySelector(s);
let data, state;
const labels = { subscriptions: "账单与订阅", warranties: "物品保修与维修", reminders: "倒计时与提醒" };
const uid = () => crypto.randomUUID?.() || `${Date.now()}_${Math.random().toString(36).slice(2)}`;
const esc = (v) => { const e = document.createElement("i"); e.textContent = v || ""; return e.innerHTML; };
async function req(url, options = {}) { const r = await fetch(url, { credentials: "same-origin", ...options }); const d = await r.json().catch(() => ({})); if (!r.ok) throw Error(d.error || "请求失败"); return d; }
async function save() { data = await req("/api/ledger", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); render(); }
function move(list, index, amount) { if (index + amount < 0 || index + amount >= list.length) return; [list[index], list[index + amount]] = [list[index + amount], list[index]]; save(); }
function siteTitle() { const n = data.settings.siteName || "HomeLedger"; $("#siteName").textContent = n; $("#mark").textContent = [...n][0] || "H"; document.title = `${n} · 管理`; }
function renderOrder() { const root = $("#order"); root.replaceChildren(); data.settings.moduleOrder.forEach((kind, index) => { const wrap = document.createElement("span"); const name = document.createElement("button"); name.textContent = labels[kind]; const up = document.createElement("button"); up.textContent = "↑"; up.disabled = index === 0; up.onclick = () => move(data.settings.moduleOrder, index, -1); const down = document.createElement("button"); down.textContent = "↓"; down.disabled = index === data.settings.moduleOrder.length - 1; down.onclick = () => move(data.settings.moduleOrder, index, 1); wrap.append(name, up, down); root.append(wrap); }); }
function detail(x) { return x.nextDate ? ` · ${x.nextDate}` : x.warrantyUntil ? ` · 保修至 ${x.warrantyUntil}` : x.targetDate ? ` · ${x.targetDate}` : ""; }
function render() { siteTitle(); renderOrder(); const panels = $("#panels"); panels.replaceChildren(); data.settings.moduleOrder.forEach((kind) => { const panel = document.createElement("section"); panel.className = "panel"; const head = document.createElement("div"); head.className = "panel-head"; head.innerHTML = `<h2>${labels[kind]}</h2>`; const add = document.createElement("button"); add.textContent = "+ 新增"; add.onclick = () => open(kind); head.append(add); panel.append(head); if (!data[kind].length) panel.insertAdjacentHTML("beforeend", '<div class="empty"><p>还没有记录</p></div>'); data[kind].forEach((item, index) => { const row = document.createElement("div"); row.className = "admin-row"; row.innerHTML = `<div class="copy"><strong>${esc(item.name)}</strong><span>${esc(item.category || "未分类")}${detail(item)}</span></div>`; [["编辑", () => open(kind, index)], ["↑", () => move(data[kind], index, -1)], ["↓", () => move(data[kind], index, 1)], ["删除", async () => { if (confirm("确认删除这条记录？")) { data[kind].splice(index, 1); await save(); } }]].forEach(([text, handler], buttonIndex) => { const b = document.createElement("button"); b.textContent = text; if (buttonIndex === 3) b.className = "delete"; b.onclick = handler; row.append(b); }); panel.append(row); }); panels.append(panel); }); }
function field(label, name, value = "", type = "text", options = "") { const control = type === "textarea" ? `<textarea name="${name}">${esc(value)}</textarea>` : type === "select" ? `<select name="${name}">${options}</select>` : `<input name="${name}" type="${type}" value="${esc(value)}">`; return `<div class="field"><label>${label}</label>${control}</div>`; }
function open(kind, index) { const blank = { id: uid(), name: "", category: "", note: "", amount: 0, cycle: "monthly", currency: "CNY", autoRenew: true, repeat: "none", advanceDays: 0, repairs: [] }; const item = index === undefined ? blank : data[kind][index]; state = { kind, index, item }; $("#eyebrow").textContent = index === undefined ? "NEW RECORD" : "EDIT RECORD"; $("#title").textContent = `${index === undefined ? "新建" : "编辑"}${labels[kind]}`; let html = `<div class="two">${field("名称", "name", item.name)}${field("分类", "category", item.category)}</div>`;
  if (kind === "subscriptions") html += `<div class="two">${field("金额", "amount", item.amount, "number")}${field("周期", "cycle", item.cycle, "select", '<option value="monthly">每月</option><option value="yearly">每年</option><option value="once">一次性</option>')}</div><div class="two">${field("下次扣费日", "nextDate", item.nextDate, "date")}${field("支付方式", "payment", item.payment)}</div>`;
  if (kind === "warranties") html += `<div class="two">${field("品牌", "brand", item.brand)}${field("型号", "model", item.model)}</div><div class="two">${field("购买日期", "purchaseDate", item.purchaseDate, "date")}${field("保修截止", "warrantyUntil", item.warrantyUntil, "date")}</div><div class="two">${field("购买金额", "purchasePrice", item.purchasePrice, "number")}${field("存放位置", "location", item.location)}</div>${field("发票/说明书链接", "link", item.link, "url")}`;
  if (kind === "reminders") html += `<div class="two">${field("日期", "targetDate", item.targetDate, "date")}${field("提前提醒天数", "advanceDays", item.advanceDays, "number")}</div>${field("重复", "repeat", item.repeat, "select", '<option value="none">不重复</option><option value="yearly">每年</option><option value="monthly">每月</option>')}`;
  html += field("备注", "note", item.note, "textarea"); $("#fields").innerHTML = html; if (kind === "subscriptions") $("[name=cycle]").value = item.cycle; if (kind === "reminders") $("[name=repeat]").value = item.repeat; $("#editor").showModal(); }
$("#editorForm").onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (state.kind === "settings") { data.settings.siteName = String(form.get("siteName") || "").trim() || "HomeLedger"; $("#editor").close(); await save(); return; } const item = { ...state.item }; for (const [key, value] of form) item[key] = value; item.amount = Number(item.amount) || 0; item.purchasePrice = Number(item.purchasePrice) || 0; item.advanceDays = Number(item.advanceDays) || 0; if (!item.name.trim()) return; item.name = item.name.trim(); if (state.index === undefined) data[state.kind].push(item); else data[state.kind].splice(state.index, 1, item); $("#editor").close(); await save(); };
document.querySelectorAll("[data-close]").forEach((b) => b.onclick = () => $("#editor").close());
$("#settings").onclick = () => { state = { kind: "settings" }; $("#eyebrow").textContent = "SITE SETTINGS"; $("#title").textContent = "站点设置"; $("#fields").innerHTML = field("站点名称", "siteName", data.settings.siteName); $("#editor").showModal(); };
$("#export").onclick = () => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); a.download = `home-ledger-${new Date().toISOString().slice(0, 10)}.json`; a.click(); };
$("#import").onclick = () => $("#file").click(); $("#file").onchange = async (event) => { try { const incoming = JSON.parse(await event.target.files[0].text()); if (!["subscriptions", "warranties", "reminders"].every((key) => Array.isArray(incoming[key]))) throw Error(); if (confirm("导入将替换当前所有数据，继续吗？")) { data = incoming; await save(); } } catch { alert("不是可用的 HomeLedger JSON 文件"); } event.target.value = ""; };
$("#logout").onclick = async () => { await req("/api/auth/logout", { method: "POST" }); location.reload(); };
async function login(event) { event.preventDefault(); try { await req("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: $("#password").value }) }); const session = await req("/api/auth/session", { cache: "no-store" }); if (!session.authenticated) throw Error("登录状态未保存，请确认浏览器允许 Cookie。"); data = await req("/api/ledger", { cache: "no-store" }); $("#login").hidden = true; $("#adminApp").hidden = false; render(); } catch (error) { $("#loginMessage").textContent = error.message; } }
$("#loginForm").onsubmit = login;
async function init() { try { const session = await req("/api/auth/session", { cache: "no-store" }); if (!session.authenticated) { $("#login").hidden = false; return; } data = await req("/api/ledger", { cache: "no-store" }); $("#adminApp").hidden = false; render(); } catch { $("#login").hidden = false; } }
init();
